// 🇬🇧 [MULTILENGUAJE 2026-08-21] English.
//
// NO es una traducción literal del español, y eso es a propósito. El español de MEITI es voseo:
// directo, cercano, sin solemnidad ("Crea tu app", "Ya puedes seguir"). Traducido palabra por
// palabra queda correcto y muerto — "Create your app without programming" es un folleto.
//
// En inglés esa misma cercanía se consigue con contracciones y frases cortas ("You're good to go",
// "Not sure where to start?"). Esa es la vara: que suene a persona, no a manual.
//
// ⚠️ Este archivo es además el MOLDE del que la IA va a sacar los demás idiomas. Un error de tono
// acá se hereda en cadena — por eso español e inglés se escriben a mano y se revisan, y recién
// después la IA genera el resto sola.

export default {
  // ——— Navigation (appears on every screen) ———
  nav_my_apps: 'My apps',
  nav_create_app: 'Create app',
  nav_credits: 'Credits',
  nav_tools: 'Tools',
  nav_marketplace: 'Marketplace',
  nav_services: 'Services',
  nav_guides: "Help",
  nav_lego_panel: 'Lego Panel',

  // ——— Shared (chat, support, session) ———
  chat_input_placeholder: 'Build me an app...',
  chat_more_examples: 'More examples',
  chat_help_aria: 'Not sure where to start?',
  send: 'Send',
  see_more: 'See more',
  see_my_apps: 'See my apps',
  support: 'Support',
  sign_in: 'Sign in',
  free_credits_badge: '{n} free credits',

  menu_expand: 'Expand menu',
  menu_collapse: 'Collapse menu',
  menu_close: 'Close menu',
  menu_open: 'Open menu',
  description: 'Description',

  // ——— Marketplace ———
  market_page_description: 'Apps already built by other users, ready to use. When you buy, the whole thing copies to your account.',
  market_seo_title: 'Marketplace of apps built with AI | MEITI',
  market_seo_description: 'Apps already built by other MEITI users, ready to use. You buy it and the whole thing copies to your account instantly.',
  market_error_load: "Couldn't load the marketplace. Try again in a bit.",
  market_error_buy: "Couldn't start the purchase.",
  sort_recent: 'Recent',
  sort_top_rated: 'Top rated',
  sort_best_selling: 'Best selling',
  market_milestone_tooltip: 'Flagged by the MEITI team as an example of good practice (Pentagon evolution milestone)',
  market_score_tooltip: 'Automatic MEITI Pentagon score. It measures code quality, not buyer opinion.',
  market_rating_tooltip: 'Rating from real buyers',
  hide_description: 'Hide description',
  show_description: 'Show description',
  cancel: 'Cancel',
  market_rate_prompt: 'Already bought it? Rate it',
  market_pick_stars: 'Pick from 1 to 5 stars.',
  market_error_rating: "Couldn't send the rating.",
  sending: 'Sending...',
  market_send_rating: 'Send rating',

  // ——— Credits and plans ———
  credits_current_balance: 'Current balance',
  credits_monthly_plans: 'Monthly plans',
  opening: 'Opening...',
  credits_manage_plan: 'Manage plan',
  credits_payment_failed: 'Your last payment failed. Update your payment method from "Manage plan" so you do not lose the renewal.',
  per_month: '/mo',
  redirecting: 'Redirecting...',
  credits_subscribe: 'Subscribe',
  credits_per_month: '{n} credits every month',
  credits_apps_per_month: 'up to {n} advanced apps a month',
  credits_auto_renew: 'renews on its own, with a month of backup if you do not spend it all',
  credits_cheaper: '{n}% cheaper than buying credits one by one',
  credits_unit: 'credits',
  credits_no_movements: 'No movements yet.',
  credits_seo_title: 'Credits | MEITI',
  credits_error_balance: 'Could not load your balance. Try again in a bit.',
  credits_error_payment: 'Could not start the payment.',
  credits_error_subscription: 'Could not start the subscription.',
  credits_error_plan: 'Could not open plan management.',
  credits_sign_in_plan: 'Sign in (from "My apps") to manage your plan.',
  credits_page_description: 'Every new app uses credits based on its complexity level.',
  credits_browser_balance: 'Balance for this browser. Sign in (from "My apps") to see your account total.',
  credits_redirecting: 'Redirecting to payment...',
  credits_cost_by_level: 'Cost by app level',
  credits_current_plan: 'Your current plan',
  coming_soon: 'Coming soon',
  credits_usage: 'Credit usage',
  credits_history: 'Transaction history',
  // 🌐 Idiomas de una app generada (ModalIdiomas en MisApps.jsx)
  lang_button: 'Languages',
  lang_title: 'Languages for "{app}"',
  lang_intro: 'Your app is written in one language. Adding another rewrites nothing: its texts get translated and each person sees it in theirs.',
  lang_current: 'Already speaks',
  lang_pick: 'Pick up to {tope} to add now',
  lang_cost: '{n} credit per language. If one fails, that credit comes back.',
  lang_add: 'Add {n} language(s)',
  lang_working: 'Translating...',
  lang_retry: 'Retry',
  lang_done_ok: '{n} texts translated',
  lang_done_partial: '{n} translated, {faltan} stayed in the original language',
  lang_failed: 'Couldn\'t do it. The credit was returned.',
  lang_none_yet: 'This app has no texts ready to translate yet. Apps created from now on are born ready.',
  lang_close: 'Close',
  // 🪟 La vidriera del marketplace (MisApps.jsx)
  my_published_badge: 'Published',
  my_view_storefront: 'View',
  my_publish_already: 'This app is already published. Use \"Publish changes\" to update what the store shows.',
  trial_chat: 'Ask',
  trial_chat_tip: 'Talk directly to whoever made this app. They answer from their support.',
  trial_chat_title_buyer: 'Ask the person who made it',
  trial_chat_title_seller: 'Someone is trying your app',
  trial_chat_greet_buyer: 'Write to whoever made this app. Ask if it fits what you need, if something can be changed, or anything else you want to know before buying.',
  trial_chat_greet_seller: 'Someone is trying your app right now. What you answer can be the difference between a sale and a trial that just runs out.',
  trial_chat_placeholder: 'Write your message',
  trial_chat_error: 'Could not send the message.',
  trial_state_live: 'Trying it now',
  trial_state_bought: 'Bought it',
  trial_state_over: 'Trial ended',
  seller_support: 'Support',
  seller_support_tip: 'Conversations with people trying your apps',
  seller_support_title: 'Your store support',
  seller_support_sub: 'People trying your apps who wrote to you',
  seller_support_empty: 'Nobody has written yet. When someone tries one of your apps and has a question, it shows up here.',
  seller_support_count: '{n} message(s)',
  seller_support_error: 'Could not load your support.',
  ago_now: 'just now',
  ago_minutes: '{m} min ago',
  ago_hours: '{h} h ago',
  ago_days: '{d} day(s) ago',
  cat_trial: 'Trial app',
  my_style: 'Style',
  my_style_tip: 'Change this app visual style. It is instant and re-forges nothing.',
  trial_session: 'Trial session',
  trial_error: 'Could not start the trial.',
  market_own_view: 'View',
  error_servidor_no_responde: 'The server did not respond. Reload the page and try again.',
  my_error_open_storefront: 'Could not open your storefront.',
  market_error_open: 'Could not open your storefront.',
  market_own_tip: 'This app is yours. Open your storefront from My apps to curate it.',
  trial_left_hours: '{h} h {m} min left',
  trial_left_minutes: '{m} min left',
  trial_over: 'Trial ended',
  trial_language_free: 'Add a language, free. One per trial.',
  trial_language_free_short: 'Free language',
  trial_language_spent: 'You already used this trial free language. Buy the app to add as many as you want.',
  trial_language_spent_short: 'Language used',
  trial_buy: 'Buy ${precio}',
  trial_start: 'Try it free',
  trial_start_tip: 'We give you your own copy for 2 hours: open it, use it, restyle it and take it to your phone. If you like it, you buy it.',
  trial_login_needed: 'This browser already has an account. Sign in to try the app.',
  qr_title: 'Open it on your phone',
  qr_help: 'Scan the code with your phone camera. The app opens full screen, nothing to install.',
  qr_button: 'QR',
  qr_tip: 'Code to open the app on your phone',
  qr_copy_link: 'Copy the link',
  qr_copied: 'Copied',
  qr_temporary: 'This link lasts a few minutes. If it expires, open the QR again.',
  qr_error: 'Could not generate the code.',
  my_republish: 'Publish changes',
  my_edit_listing: 'Edit listing',
  my_edit_listing_tip: 'Change the title, description, category, video or price shown in the store, or remove it from the store.',
  my_edit_listing_title: 'Edit store listing',
  my_edit_listing_note: 'Changes show up in the store right away. To update the app itself, use "Publish changes".',
  my_loading_listing: 'Loading the listing...',
  my_save_changes: 'Save changes',
  my_saving: 'Saving...',
  my_error_edit_listing: 'Could not save the changes.',
  my_category_missing: 'Previous category (no longer exists)',
  my_unpublish: 'Remove from store',
  my_unpublish_note: 'It stops being shown and sold. People who already bought it keep it, and you can publish it again anytime.',
  my_unpublish_confirm: 'Yes, remove it',
  my_unpublishing: 'Removing...',
  my_error_unpublish: 'Could not remove it from the store.',
  my_republish_tip: 'Replaces what the store shows with a fresh copy of your app. The sample data you loaded into the storefront is lost.',
  my_confirm_republish: 'What is published will be replaced with a fresh copy of your app.\n\nThe sample data you loaded into the storefront does NOT travel: the new copy is born empty and you will have to load it again with "View".\n\nContinue?',
  my_error_republish: 'Could not publish the changes.',
  my_view_storefront_tip: 'Opens the copy your buyer sees. Whatever you put here is the sample data testers will see.',
  credits_spend: 'Credit spend',
  credits_movement: 'Credit movement',
  plan_basic: 'Basic',
  plan_mid: 'Mid',
  plan_advanced: 'Advanced',

  // --- Guides ---
  guide_page_description: "So you are not guessing: how the Wizard works and how to get the most out of it.",
  guide_sec_wizard_title: "How the Wizard works, step by step",
  guide_sec_wizard_subtitle: "The 8 steps from opening MEITI to having your app ready.",
  guide_sec_ai_title: "How the AI thinks (and why your words matter)",
  guide_sec_ai_subtitle: "Before you write your request, it helps to know what you are talking to.",
  guide_sec_checklist_title: "What to keep in mind when writing your request",
  guide_sec_checklist_subtitle: "A short checklist. Cover these five points and you are on the right track.",
  guide_sec_tips_title: "How to write a good request",
  guide_sec_tips_subtitle: "Five tips so the AI gets what you want from the first message.",
  guide_sec_market_title: "Sell ready-made templates",
  guide_sec_market_subtitle: "Marketplace: turn one of your apps into a product other people buy.",
  guide_sec_services_title: "Offer custom services",
  guide_sec_services_subtitle: "Services: work directly with clients, with payment protected by milestones.",
  guide_sec_devtips_title: "Prompting with selling in mind",
  guide_sec_devtips_subtitle: 'The same tips from the "For you" tab apply. These are extra.',
  guide_wizard_1_title: "1. Language",
  guide_wizard_1_text: "You pick which language your app will be in: text, buttons, everything.",
  guide_wizard_2_title: "2. Who is it for?",
  guide_wizard_2_text: "Personal use, or for a company or team. This only groups your apps in the system, it does not change what the app can do.",
  guide_wizard_3_title: "3. App level",
  guide_wizard_3_text: "Basic (1-2 screens, the essentials), Complete (real daily use) or Advanced (the most complete version possible). Each level costs more or fewer credits, and tells the AI how much to build.",
  guide_wizard_4_title: "4. Tell us what you want",
  guide_wizard_4_text: "You write what you need in your own words. The more specific, the better it starts. There are tips further down.",
  guide_wizard_5_title: "5. Short questions",
  guide_wizard_5_text: "We ask you what is missing: what data you will store, whether you need to connect something external, whether several people will each have their own account.",
  guide_wizard_6_title: "6. Visual style",
  guide_wizard_6_text: "You pick a color palette from a curated list.",
  guide_wizard_7_title: "7. Building and review",
  guide_wizard_7_text: "Gemini writes the code, an automatic check (the Pentagon) reviews it and even tests the app by clicking through it for real before approving. We let you know when it is ready.",
  guide_wizard_8_title: '8. It is in "My apps"',
  guide_wizard_8_text: "If something is not right, you can ask for changes straight from there. No need to start over.",
  guide_ai_1_title: "It cannot read your mind",
  guide_ai_1_text: "The AI only knows what you wrote in the message, not what you are picturing in your head. If you did not write it, for the AI it does not exist.",
  guide_ai_2_title: "It fills gaps with its own judgment",
  guide_ai_2_text: "Anything you did not spell out, it decides on its own. Sometimes it gets it right, sometimes not. The more you fill in, the less it has to guess.",
  guide_ai_3_title: "It works by resemblance, not magic",
  guide_ai_3_text: 'It predicts what to build by comparing your request to millions of similar examples it has seen. A more specific request looks more like "a real app" and less like a loose idea.',
  guide_ai_4_title: "It misses tone and anything unsaid",
  guide_ai_4_text: 'It is not a person: it does not interpret a "something like..." or read between the lines. Whatever is not clearly written does not count.',
  guide_checklist_1_title: "What data you will store",
  guide_checklist_1_text: 'The "fields" of each thing the app handles. For example, in a task: title, due date, whether it is done.',
  guide_checklist_2_title: "What you will do with that data",
  guide_checklist_2_text: "View, add, edit, delete, search, filter. Name them, do not take them for granted.",
  guide_checklist_3_title: "Who is going to use it",
  guide_checklist_3_text: "Just you, or several people each with their own account.",
  guide_checklist_4_title: "If it needs to pull something from outside",
  guide_checklist_4_text: "Weather, a map, another AI. Name it even if you do not have the key yet.",
  guide_checklist_5_title: "How big you want it",
  guide_checklist_5_text: "You already pick that with the Basic, Complete or Advanced level in step 3. No need to repeat it in the text.",
  guide_tips_1_title: "Be specific about WHAT you will store",
  guide_tips_1_text: '"A task list" is vague. "Tasks with a title, a due date and whether they are done" already gives the app real shape.',
  guide_tips_2_title: "Name the actions you need",
  guide_tips_2_text: "View, add, edit, delete. If you do not mention them, the app starts with only the basics.",
  guide_tips_3_title: "Do you need data from another service?",
  guide_tips_3_text: 'Say so, for example "I want to see the real weather". MEITI sets up a Settings field so you can add your own key LATER. You do not need it right now.',
  guide_tips_4_title: "Several people, each with an account?",
  guide_tips_4_text: "Say so and the login is built for you, with a code by email. You do not code any of that.",
  guide_tips_5_title: "It does not have to be perfect the first time",
  guide_tips_5_text: 'Once it is built, you can keep asking for changes from "My apps".',
  guide_market_1_title: "Publish a ready-made template",
  guide_market_1_text: "You pick one of your apps that is already ONLINE and approved. Quality floor: it needs a stable Pentagon score of 75 or higher, the same floor normal approval already requires.",
  guide_market_2_title: "Revenue split",
  guide_market_2_text: "70% for you, 30% for the platform on every sale. The Developer Plan, a separate subscription, lowers that percentage based on your volume.",
  guide_market_3_title: "What happens when someone buys it",
  guide_market_3_text: "It gets cloned in full for the buyer. You stay the owner of the original and can keep selling it.",
  guide_services_1_title: "Set up your profile",
  guide_services_1_text: 'Portfolio and whether you take retainers, from your dev panel under "Services".',
  guide_services_2_title: "Automatic matching",
  guide_services_2_text: "The client builds their brief by chatting with the AI, and the system suggests you as a match based on what you offer.",
  guide_services_3_title: "Escrow by milestone",
  guide_services_3_text: "The client payment is held in escrow and released milestone by milestone, as the client approves each one. You never get paid up front without delivering.",
  guide_services_4_title: "Fixed-price packages",
  guide_services_4_text: "You can also sell service packages at a closed price, skipping the brief and the back and forth.",
  guide_services_5_title: "Your reputation builds itself",
  guide_services_5_text: "The trust score and the badge (Standard, Verified or Elite) are calculated from your real history of sales and reviews. They cannot be inflated by hand, not even by you.",
  guide_devtips_1_title: "Think of someone using it without you there",
  guide_devtips_1_text: "If you are going to publish it, be more explicit about validation and empty states, meaning what shows up when there is no data yet. Whoever buys it will not be able to ask you.",
  guide_devtips_2_title: "Advanced level if it is for selling",
  guide_devtips_2_text: 'That way it includes everything a buyer would expect from a "pro" app: filters, history, statistics.',
  guide_devtips_3_title: "Reuse before reinventing",
  guide_devtips_3_text: "The system already prefers reusing existing molds when they are compatible. Mentioning a feature similar to something you already built helps the AI recognize it.",
  guide_example_vague: "I want an app for my expenses.",
  guide_label_vague: "Vague",
  guide_label_clear: "Clear",
  guide_example_clear: "I want to log my monthly expenses: date, amount, category (food, transport, etc.) and an optional note. I want to see them in a list, be able to edit or delete them, and see the total spent for the month.",

  guide_seo_title: "How to ask for your app, step by step | MEITI Help",
  guide_seo_description: "Learn how the MEITI AI assistant works and how to write the ideal request so the first version of your app comes out right.",
  guide_tab_why: 'Why MEITI',
  guide_tab_you: "For you",
guide_tab_why: "Why MEITI",

  why_hero_title: "The difference isn't that it writes your app. It's that it tests it before handing it over.",
  why_hero_text: "Any AI builder returns code in minutes. The trouble shows up later: does it actually work? At MEITI, no app reaches you without passing three automatic checks — and if something fails, the system repairs it on its own before you ever see it.",

  why_sec_control_title: "The three checks every app passes",
  why_sec_control_subtitle: "Automatic, on every app and every new page. If any one fails, the app isn't approved.",
  why_control_1_title: "Pentagon: the structure",
  why_control_1_text: "A deterministic analysis (no AI, same result every time) measures five axes: data structure, dependencies, information flows, render efficiency and logic. If the score falls short, it doesn't pass.",
  why_control_2_title: "Code review",
  why_control_2_text: "A second AI reads the code looking for real defects: data that never gets saved, fields that overwrite each other, screens that would come up empty, information leaking between users. It doesn't review taste — it reviews what breaks.",
  why_control_3_title: "Real-use test",
  why_control_3_text: "A robot opens your app the way a person would: it navigates, fills in forms, clicks the buttons and checks that the data shows up. Only if it can genuinely use the app does the app get approved.",

  why_sec_cura_title: "It learns from every defect, for every app",
  why_sec_cura_subtitle: "This is what no other builder does: the system improves on its own as it's used.",
  why_cura_1_title: "The defect is fixed once",
  why_cura_1_text: "When a problem is found, only the affected piece is repaired — the whole app is never rebuilt. Whatever was already right stays exactly as it was.",
  why_cura_2_title: "And it never comes back",
  why_cura_2_text: "If the same kind of defect shows up in two different apps, the system turns it into a permanent rule. From then on, no new app is born with that defect again.",
  why_cura_3_title: "The pieces add up",
  why_cura_3_text: "Every app contributes its already-tested components to a shared library. The more MEITI is used, the faster and better the next apps are born.",

  why_sec_tuya_title: "The app is genuinely yours",
  why_sec_tuya_subtitle: "Without being tied to us forever.",
  why_tuya_1_title: "Desktop installer",
  why_tuya_1_text: "Windows, Mac and Linux. The app runs on the computer with its own local database, without depending on the internet or on our servers.",
  why_tuya_2_title: "Android and iOS",
  why_tuya_2_text: "The complete mobile project is generated, ready to build and install on the phone.",
  why_tuya_3_title: "The full source code",
  why_tuya_3_text: "You can take the whole project with you, with its automatic build workflows already set up for GitHub. It's your code: keep working on it with whoever you like.",

  why_sec_backend_title: "With everything behind the scenes already solved",
  why_sec_backend_subtitle: "What normally requires a separate backend comes included here.",
  why_backend_1_title: "Its own database per app",
  why_backend_1_text: "Each app is born with its own data store, isolated from the rest. You don't share a database with anyone and there's nothing to configure.",
  why_backend_2_title: "Users and sessions",
  why_backend_2_text: "Login by email code — no passwords to remember or lose. Each user sees only their own data.",
  why_backend_3_title: "Secure external connections",
  why_backend_3_text: "If your app uses an outside service (an AI, a weather service, a payments API), the secret key is kept on the server side and never travels to your users' browsers.",
  why_backend_4_title: "Built-in payments",
  why_backend_4_text: "You can charge inside your app and receive the money in your own account, without setting up a payment gateway yourself.",

  why_sec_vs_title: "Compared with the other options",
  why_vs_trad_title: "Hiring development",
  why_vs_trad_text: "Months of waiting and high budgets. Every change depends on someone else's schedule. Here you ask for the change and you have it.",
  why_vs_otros_title: "Other AI builders",
  why_vs_otros_text: "They hand you the code and their job ends there: if the app has a defect, you find it by using it. MEITI tests it first, repairs it on its own, and learns from what it found.",
  why_vs_nocode_title: "No-code platforms",
  why_vs_nocode_text: "They give you fixed pieces to assemble and you stay inside their system forever. Here the code is yours and you can take it with you.",

  why_cierre_title: "Start by describing your idea",
  why_cierre_text: "You don't need to know about technology or have it all figured out. The assistant asks you a few short questions and takes care of the rest.",
  why_cierre_boton: "Create my app",
  guide_tab_devs: "For developers",
  guide_example_title: "One example, the same request written two ways",
  guide_example_caption: "The one on the right gives the AI something concrete to build. The one on the left forces it to guess everything.",

  // --- Services ---
  svc_page_title: "Custom services",
  svc_tab_client: "Request a build",
  svc_tab_retainer: "Monthly retainer",
  svc_tab_dev: "I offer services",
  svc_ex_appointments: "Appointment system for a clinic",
  svc_ex_store: "Online store with payments",
  svc_ex_delivery: "Delivery app with tracking",
  svc_ex_panel: "Internal panel for my team",
  svc_ex_integration: "Connect my system to another one",
  svc_loading_request: "Loading your request...",
  svc_input_placeholder: "I need something built...",
  svc_pick_dev: "Pick a developer",
  svc_working_with: "You will work with",
  svc_searching_devs: "Looking for available devs...",
  svc_define_milestones: "Define the project milestones",
  svc_milestone_example: "e.g. Design and first screen",
  svc_awaiting_confirmation: "Awaiting confirmation",
  svc_milestones: "Milestones",
  svc_confirm_identity: "Confirm it is you",
  svc_code_sent_to: "We sent a code to",
  svc_email_placeholder: "you@email.com",
  svc_code_placeholder: "123456",
  svc_thanks_review: "Thanks for your review!",
  svc_rate_dev: "Rate the developer",
  svc_comment_optional: "Comment (optional)",
  svc_dev_email: "Developer email",
  svc_monthly_amount: "Monthly amount (USD)",
  svc_active_retainers: "Your active retainers",
  loading: "Loading...",
  svc_profile_saved: "Profile saved.",
  svc_skills: "Skills (comma separated)",
  svc_skills_placeholder: "react, node, sqlite",
  svc_tools: "Tools (comma separated)",
  svc_tools_placeholder: "figma, git, docker",
  svc_username: "Username",
  svc_username_placeholder: "How you want to be seen on MEITI",
  svc_avatar: "Your profile avatar",
  svc_portfolio: "Portfolio (one URL per line)",
  svc_title: "Title",
  svc_title_placeholder: "e.g. Full-stack developer specialized in business apps",
  svc_desc_placeholder: "Say in one line what kind of projects you take on and who for.",
  svc_packages: "Fixed-price service packages",
  svc_package_example: "e.g. I set up your WhatsApp chatbot with AI",
  svc_package_includes: "What it includes...",
  svc_package_price: "Price in USD, e.g. 150",
  svc_package_days: "Days to deliver, e.g. 3",
  svc_no_packages: "You have no packages yet.",

  svc_seo_title: "Custom services with real developers | MEITI",
  svc_seo_description: "Tell us about your project and we connect you with a developer. Payment held in escrow by milestone, released as you approve each delivery.",
  svc_page_description: "A build made by a real dev, shaped from your request, with payment held in escrow until you approve each delivery.",
  svc_chat_intro: "Tell us what you need. A couple of questions and we put together the request to hand to a dev.",
  showcase_fallback_title: "What you can do with MEITI",

  // --- Mis apps ---
  my_page_description: "Your apps, requests and jobs in one place.",
  my_tab_apps: "Apps",
  my_tab_requests: "Requests",
  my_tab_jobs: "Jobs",
  my_no_apps: "You have not requested any app with this account yet.",
  my_no_custom_requests: "You have not requested any custom build yet.",
  my_no_assigned_jobs: "You have no service requests assigned yet.",
  my_planning_note: "Planning, timelines, ideas. Never code.",
  my_ask_about_job: "Ask something about this job...",
  my_complexity: "Complexity:",
  my_client_budget: "Client estimated budget:",
  my_delete_project: "Delete project",
  my_generating: "Building your app...",
  my_ai_connection_failed: "Could not finish because the AI connection failed.",
  my_platform: "Platform",
  my_published: "Published!",
  my_published_note: "It is now visible in the marketplace for others to buy.",
  my_publish: "Publish to marketplace",
  my_revenue_note: "You keep 70% of every sale (standard commission).",
  my_app_desc_placeholder: "What the app does, who it is for...",
  my_demo_link: "Demo video link (optional)",
  my_category: "Category",
  my_category_general: "General",
  my_price: "Price (USD)",
  done: "Done",
  my_write_here: "Write here...",

  my_seo_title: "My apps | MEITI",
  my_login_title: "Sign in to My apps",
  login_code_note: "We send you an access code. No passwords.",
  login_peek_prompt: "Rather look around before signing in?",
  login_send_code: "Send code",
  login_verify: "Verify",
  login_verifying: "Verifying...",

  login_check_email: "Check your email",
  login_code_6_digits: "We sent a 6-digit code to",

  svc_picked_from_profile: "You picked this developer straight from their profile, so automatic matching is skipped.",
  svc_complete_profile: "Complete your profile so clients putting together a request see you as an option.",
  svc_no_payout: "You have not set up how you get paid. Without this you cannot receive milestones or retainers.",
  my_review_done: "Review finished. You can apply or discard now.",
  my_invite_devs: "Invite other devs and earn a % of every sale they make. It never costs them more:",
  profile_pick_avatar: "Pick an avatar and how you want to be identified.",
  profile_nickname_note: "Never your real name. It is a nickname, just to identify you here.",
  support_what_need: "What do you need?",
  support_to_wizard: "We take you to the build assistant.",
  support_about_what: "What do you want to tell us about?",
  support_which_app: "Which of your apps is it about?",

  // --- Categorias ---
  sort_price_asc: "Price ↑",
  sort_price_desc: "Price ↓",
  market_buy: "Buy",
  market_subscribe: "Subscribe",
  market_per_month: "/mo",
  market_zone_products: "Products",
  product_sub_active: "Subscription up to date",
  product_sub_past_due: "Payment pending — there's a grace period before it deactivates",
  product_sub_cancelled: "Cancelled — stays active until the end of the grace period",
  product_sub_manage_billing: "Manage billing",
  market_subscribe_login_needed: "You need to sign in to subscribe — this is a real account, not a trial.",
  market_subscribe_ask_title: "What's your business called? (this builds your instance's link)",
  by: "by",
  market_audit: "MEITI audit",
  market_no_video: "No video yet.",
  market_no_description: "No description yet.",
  cat_finance: "Finance",
  cat_tasks: "Tasks",
  cat_commerce: "Commerce",
  cat_education: "Education",
  cat_health: "Health and fitness",
  cat_industrial: "Industrial",
  cat_communication: "Communication",
  cat_data: "Data and analytics",
  cat_home: "Home",
  cat_events: "Events",
  cat_content: "Content",
  cat_general: "General",

  language: "Language",

  sign_out: "Sign out",
  my_notify_ready: "Notify me when it is ready",
  my_notify_ready_plural: "Notify me when they are ready",
  app_state_ready: "Ready",
  app_state_building: "Building",
  app_state_error: "Has an error",
  app_state_review: "In review",
  app_screens_one: "{n} screen",
  app_screens_many: "{n} screens",
  app_no_screens: "No screens",

  my_in_progress: "In progress",
  my_see_dev_tools: "See Dev Tools",
  my_app_ready_to_build: "You have an app ready to build",
  my_build_now: "Build now",
  my_trial_waiting: "You have a free trial waiting",
  my_try_now: "Try it now",
  discard: "Discard",
  my_build_first: "Build my first app",
  retry: "Retry",
  my_export: "Export",
  my_installer: "Installer",
  my_publish_short: "Publish",
  my_request_change: "Request a change",
  my_open: "Open",
  my_cancel_refund: "Cancel and refund credit",
  refresh: "Refresh",
  my_test: "Test",
  my_apply_changes: "Apply changes",
  my_see_marketplace: "See marketplace",
  close: "Close",
  copy: "Copy",
  my_keep_talking: "Keep talking",
  accept: "Accept",
  reject: "Reject",
  my_remove_flag: "Remove flag",
  my_remove_from_account: "Remove from my account",
  my_generate: "Generate",
  my_recover: "Recover",
  less: "Less",
  more: "More",
  my_sync: "Sync",
  my_confirm_start: "Confirm and start",
  my_still_reviewing: "Still being reviewed",

  my_opening_payment: "Opening payment...",
  my_recovering: "Recovering...",
  my_creating: "Creating...",

  my_removing: "Removing...",

  credits_account_total: "Your account total ({email}).",

  // --- Historial de creditos (etiquetas que guarda el backend) ---
  mov_forge_app: 'Build "{app}" ({nivel} level)',
  mov_forge_failed: "The build did not finish",
  mov_manual_adjust: "Manual adjustment by the architect",
  mov_dev_trial_bonus: "Developer Plan free trial activation bonus ({dias} days)",
  mov_change_request: 'Change request: "{resumen}"',
  mov_generate_page: 'Generate page "{pagina}"',
  mov_welcome_credits: "Welcome credits for signing up",
  mov_tablero_pieza_ia: "Piece generated by the Forge in the Tablero",
  mov_tablero_pagina: "Page saved in the Tablero",
  mov_editor_claude: "Message to the AI Editor",
  mov_agente_editor_dev: "Message to the AI Editor's agent",

  showcase_title: "Get inspired by what others built",
  showcase_a_creator: "a MEITI creator",

  credits_spent_month: "Spent this month",
  credits_spent_total: "Spent in total",
  credits_bought_total: "Bought in total",

  tools_brick_library: "Library",
  tools_bricks_premium: "Bricks (Premium)",
  tools_tablero: "Tablero",
  tablero_titulo: "The Tablero",
  tablero_subtitulo: "Arrange your app's pieces on the real grid. One page at a time.",
  tablero_candado_mensaje: "The Tablero is a paid tool: it unlocks with an active plan, or if you've already spent this much as the cheapest plan this month.",
  tablero_sin_apps: "You don't have any app available to open in the Tablero right now.",
  tablero_abrir_boton: "Open in the Tablero",
  tablero_seguir_editando: 'Continue editing',
  tablero_abriendo: "Opening...",
  tablero_error_cargar_apps: "Could not load your apps.",
  tablero_error_abrir: "Could not open the Tablero.",
  tablero_error_cargar: "Could not load this page.",
  tablero_error_guardar: "Could not save the page.",
  tablero_error_aplicar: "Could not apply the change.",
  tablero_error_descartar: "Could not discard the change.",
  tablero_error_construir: "Could not build the mold.",
  tablero_salir: "Exit",
  tablero_volver: "Back",
  tablero_aplicar: "Apply changes",
  tablero_aplicando: "Applying...",
  tablero_descartar: "Discard",
  tablero_descartando: "Discarding...",
  tablero_confirmar_aplicar: "This replaces your live app with what you built here. Continue?",
  tablero_confirmar_descartar: "Everything you built in this Tablero session gets discarded, without touching your live app. Continue?",
  tablero_pagina_cobrada: "Page saved. 1 credit was charged.",
  tablero_pagina_gratis: "Page saved, no charge.",
  tablero_sin_pagina: "This app has no pages.",
  tablero_pagina_vacia: "This page is empty. Add a piece from the left.",
  tablero_buscar_piezas: "Search pieces...",
  tablero_es_compuesto: "Compound mold (built in the Tablero)",
  tablero_pieza_nueva: "New piece",
  tablero_elige_pieza: "Pick a piece on the canvas to see its properties.",
  tablero_prop_titulo: "Title",
  tablero_prop_ancho: "Width",
  tablero_prop_orden: 'Order',
  tablero_mover_arriba: 'Move up',
  tablero_mover_abajo: 'Move down',
  tablero_quitar_pieza: "Remove from page",
  tablero_guardar_pagina: "Save page",
  tablero_construir_titulo: "Build a mold",
  tablero_agregar_a_pagina: 'Add to the page',
  tablero_editar_molde: 'Edit this mold',
  tablero_editar_con_claude: 'Edit this mold with Claude',
  tablero_editar_manual: 'Edit the code by hand',
  tablero_pieza_manual_boton: 'Build it yourself',
  tablero_pieza_ia_boton: 'Ask the Forge',
  tablero_pieza_ia_titulo: 'Ask the Forge',
  tablero_pieza_ia_placeholder: 'Describe the piece you need: what it does, what data it shows or saves...',
  tablero_pieza_ia_costo_aviso: 'You only get charged if the piece comes out right. If the Forge can\'t generate it, nothing is charged.',
  tablero_pieza_ia_enviar: 'Ask the Forge',
  tablero_pieza_ia_pidiendo: 'Asking...',
  tablero_pieza_ia_generando: 'The Forge is generating your piece. You can keep arranging the page in the meantime.',
  tablero_pieza_ia_exito: 'Piece ready: "{nombre}". You can add it from the library now.',
  tablero_pieza_ia_reuso: 'A piece for this already existed: "{nombre}", added to the page.',
  tablero_pieza_ia_error: 'The Forge could not generate the piece: {error}',
  tablero_error_pedir_pieza: 'Could not request the piece.',
  tablero_editar_titulo: 'Edit mold',
  tablero_divergido_aviso: 'This mold was edited outside the Tablero (with Claude or the manual editor) since the last time it was saved here. Editing and saving from here will overwrite that code.',
  tablero_confirmar_editar_divergido: 'This mold was edited outside the Tablero. Editing and saving from here will overwrite that code with whatever you build in this constructor.\n\nEdit anyway?',
  tablero_guardar_cambios_molde: 'Save changes',
  tablero_construir_boton: "Build and add",
  tablero_construyendo: "Building...",
  tablero_nombre_molde: "Mold name",
  tablero_tabla_datos: "Data table",
  tablero_tabla_hija: "Child table",
  tablero_columna_fk: "Column pointing to the parent",
  tablero_campos_maestro: "Fields",
  tablero_campos_detalle: "Detail fields",
  tablero_agregar_campo: "Add field",
  tablero_agregar_detalle: "Add a detail (master-detail)",
  tablero_campo_columna: "column",
  tablero_campo_etiqueta: "label",
  tablero_campo_texto: "text",
  tablero_renombrar_pagina: "Rename page",
  tablero_mover_pagina_izquierda: "Move left",
  tablero_mover_pagina_derecha: "Move right",
  tablero_error_renombrar_pagina: "Could not rename the page.",
  tablero_error_reordenar_paginas: "Could not change the page order.",
  tablero_renombrar_molde: "Rename this piece",
  tablero_error_renombrar_molde: "Could not rename the piece.",
  tools_claude_editor: "AI Editor",
  tools_pentagon_audit: "Pentagon audit",
  tools_seo_title: "Developer tools | MEITI",
  tools_seo_description: "Advanced tools panel for developers on the Developer Plan.",
  tools_page_title: "Developer tools",
  tools_subscribe_dev: "Subscribe to the Developer Plan",
  lego_seo_title: "Lego Panel | MEITI",
  lego_seo_description: "Build a small panel for free by assembling pieces that already work, with no new code.",
  lego_unavailable: "Lego Panel is not available here yet.",
  showcase_top_devs: "Top rated devs",
  trial_need_skill_bio: "Add at least one skill and a short bio.",
  trial_activation_failed: "Could not activate the trial.",
  trial_skills_placeholder: "Skills (e.g. React, Node, SQL)",
  trial_bio_placeholder: "Short bio (one line about you)",
  trial_activating: "Activating...",
  trial_activate: "Start free trial",
  made_with_meiti: "Made with MEITI",
  tap_one_to_start: "Tap one to start yours from that idea.",

  nosession_needs_account: "{nombre} needs an account. It is free and takes a minute.",
  nosession_signin_credits: "Sign in and get {n} free credits",

  tools_page_description: "Library, Audit and Marketplace are free for any registered dev. AI Editor and Lego Panel are part of the Developer Plan.",

  // --- Industrial (AutoMach) ---
  ind_seo_title: "Automate your industrial machine with AI | MEITI",
  ind_seo_description: "Connect your PLC or real machine over Modbus or OPC-UA and generate a custom control app that runs on your own network.",
  ind_page_description: "Connect your PLC or real machine and we build a custom control app.",
  ind_chat_intro: "Tell me what machine you want to automate. A couple of questions and we set up the project.",
  ind_input_placeholder: "Automate a machine for me...",
  ind_ex_irrigation: "Control greenhouse irrigation",
  ind_ex_packer: "Control panel for a packaging machine",
  ind_ex_coldroom: "Monitor cold room temperature",
  ind_ex_lighting: "Automate plant lighting",
  ind_review_note: "Does it all look right? You can fix any answer or add something before we build the app.",
  ind_edit_answer: "Edit this answer",
  ind_back_to_project: "Back to project",
  ind_save_continue: "Save changes and continue",
  ind_all_good: "All good, continue",
  ind_preparing: "Setting up your project...",
  ind_your_project: "Your project",
  ind_hardware: "Hardware",
  ind_pending_confirm: "Pending confirmation",
  ind_no_points: "No points yet.",
  ind_status: "Status",
  ind_review_interview: "Review interview",
  ind_go_my_apps: "Go to My apps",
  ind_building: "Building your control app...",
  ind_takes_a_minute: "This can take a minute. Do not close this screen.",
  ind_app_coming: "Your app is on its way!",
  ind_automate_another: "Automate another machine",
  ind_start_over: "Start over",
  ind_login_title: "Sign in to continue",
  ind_error_edit: "Could not edit the interview.",
  ind_error_project: "Could not create the project.",
  ind_error_scanner: "Could not download the scanner.",
  ind_error_upload: "Could not upload the file.",
  ind_error_bad_profile: "The file is not a valid perfil.json.",
  ind_error_generate: "Could not generate the app.",
  save: "Save",
  add: "Add",

  // --- Perfil de creador ---
  prof_summary: "Summary",
  prof_apps_for_sale: "Apps for sale",
  prof_reviews: "Reviews",
  prof_seo_title: "Creator profile | MEITI",
  prof_error_load: "Could not load this profile.",
  prof_not_found: "This creator does not exist.",
  prof_page_title: "Creator profile",
  prof_page_description: "A dev public page: their services, their reputation and how to reach them.",
  prof_verified: "Verified identity",
  prof_hire: "Hire service",
  prof_see_market_apps: "See apps in the market",
  prof_skills: "Skills",
  prof_no_profile: "They have not completed their profile yet.",
  prof_no_portfolio: "They have not added anything to their portfolio yet.",
  prof_no_reviews: "No reviews yet.",
  prof_custom_service: "Custom service",
  prof_no_apps: "No published apps yet.",
  prof_need_custom: "Need something custom?",
  prof_tell_project: "Tell us about your project. The AI puts the request together and sends it straight to this developer.",
  prof_packages: "Available packages",
  prof_no_packages: "No fixed-price packages yet.",

  prof_no_packages_own: 'You have no packages yet. Create one from "I offer services".',

  // --- Cierre de la migracion ---
  wiz_own_login: "Your app will have its own login",
  wiz_error_create: "Could not create the app.",
  wiz_error_create_conn: "Failed to create the app.",
  wiz_sender_placeholder: 'Sender, e.g. "My Company <codes@mycompany.com>"',
  ind_building_app: "Building your app...",
  tools_complete_profile: 'Complete your profile in Services, under "I offer services"',
  login_default_title: "Sign in",
  prof_unavailable: "Not available",
  prof_tab_services: "Services",
  prof_tab_portfolio: "Portfolio",
  prof_available: "Available",
  prof_error_save: "Could not save your profile.",
  prof_your_profile: "Your MEITI profile",
  chat_back_to_last: "Back to the last message",
  showcase_automate: "Automate your machine",
  showcase_create_app: "Create your app",
  showcase_build_panel: "Build your panel",
  showcase_more_panels: "More panels",
  showcase_more_apps: "More apps",
  sup_app_bug: "Bug in an app",
  sup_app_bug_desc: "Something does not work as you expected in an app we built for you.",
  sup_payment: "Payment or refund",
  sup_payment_desc: "A problem with a charge, or you want to ask for a refund.",
  sup_idea_desc: "An idea to make MEITI better.",
  sup_account: "Account or access",
  sup_account_desc: "You cannot sign in, or something is off with your account.",
  sup_other_desc: "Something that does not fit the ones above.",
  error_generic_dot: "Something went wrong.",
  sup_new_app: "Create a new app",
  sup_report_desc: "Report a problem, a payment, or leave a suggestion.",
  sup_tell_what_happened: "Tell me what happened, with as much detail as you can.",
  svc_error_load_request: "Could not load your request.",
  svc_pick_from_list: "Pick a developer from the list.",
  svc_need_milestone: "Define at least one milestone with a title and an amount.",
  svc_error_assign: "Could not assign the developer.",
  svc_error_release: "Could not release the payment.",
  svc_assign_milestones: "Assign and create milestones",
  svc_approve_release: "Approve and release payment",
  svc_error_send_code: "Could not send the code.",
  svc_wrong_code: "Wrong code.",
  svc_error_retainer: "Could not start the retainer.",
  svc_you_pay: "You pay",
  svc_you_get_paid: "You get paid",
  svc_error_payouts: "Could not start the payout setup.",
  svc_your_avatar: "Your avatar",
  svc_error_package: "Could not create the package.",
  my_unpaid: "Unpaid",
  my_untitled_request: "Untitled request",
  my_error_assistant: "Could not reach the assistant.",
  my_error_reply: "Could not reply to the request.",
  my_error_build: "Could not start the build.",
  my_error_installer: "Could not download the installer.",
  my_retrying: "Retrying your request. The app goes back to review.",
  my_error_cancel: "Could not cancel the request.",
  my_error_preview: "Could not generate the preview.",
  my_error_sync: "Could not sync the data.",
  my_already_synced: "Everything was already up to date, no new data.",
  my_error_apply: "Could not apply the change.",
  my_error_discard: "Could not discard.",
  my_error_discard_change: "Could not discard the change.",
  my_hardware_unconfirmed: "Hardware not confirmed",
  my_generating_short: "Generating...",
  my_error_publish: "Could not publish.",
  my_error_message: "Could not process the message.",
  my_error_start_change: "Could not start the change.",
  my_tell_change: "Tell me what you want to add, change or remove.",

  my_error_retry: "Could not retry.",
  my_confirm_delete: "Delete this project? This cannot be undone.",
  my_error_recover: "Could not recover the app.",
  my_error_export: "Could not export the app.",
  my_error_remove: "Could not remove the app from your account.",
  my_error_page: "Could not generate the page.",
  my_generating_page: "Generating your page. The app goes back to review.",
  my_error_discard_page: "Could not discard the page.",
  my_error_update: "Could not apply the update.",
  my_error_retry_request: "Could not retry the request.",
  my_sell_a_lot: "Selling a lot? Pay less →",
  my_setup_payouts: "Set up how you get paid →",
  svc_packages_note: "A Fiverr-style shortcut for repeatable work. No AI chat needed: the client buys straight from your profile.",

  // --- Dev tools (Lego Panel, Herramientas) ---
  dt_confirm: "Confirm",
  dt_back: "Back",
  dt_search: "Search...",
  dt_no_results: "No results.",
  dt_mold_name: "Mold name",
  dt_save_as_own: "Save it as your own mold in one of your apps:",
  dt_loading_apps: "Loading your apps...",
  dt_no_own_apps: "You have no apps of your own yet. Create one first from the wizard.",
  dt_pick_app: "Pick an app...",
  dt_cloning: "Cloning...",
  dt_error_clone: "Could not clone the mold.",
  dt_search_by_name: "Search by name or id...",
  dt_error_undo: "Could not undo.",
  dt_undo_tooltip: "Go back to the version before the last save",
  dt_undoing: "Undoing...",
  dt_undo: "Undo",
  aud_matter: "Matter",
  aud_energy: "Energy",
  aud_information: "Information",
  aud_time: "Time",
  aud_intelligence: "Intelligence",
  aud_monolith: "Possible monolith: one mold holds too much logic or state.",
  aud_collapsed_field: "A field is collapsed because its container is missing flex-1.",
  aud_unmaterialized: "Some molds are not materialized yet (volatile code).",
  aud_no_settings: "Multi-page app with no profile or settings section.",
  aud_error: "Could not audit this app.",
  aud_no_apps: "You have no approved (ONLINE) apps to audit yet.",
  aud_auditing: "Auditing...",
  aud_would_pass: "Would pass",
  aud_would_fail: "Would not pass",
  aud_points_to_check: "Points to check",
  ed_error_load: "Could not load the code.",
  ed_error_assistant: "Could not reach the assistant.",
  ed_unavailable: "The AI Editor is not available right now.",
  ed_no_own_molds: "You have no apps with your own molds yet.",
  ed_edit_with_code: "Edit with Code/View",
  ed_yes_load: "Yes, load it",
  ed_loading_editor: "Loading editor...",
  ed_error_save: "Could not save.",
  ed_restored: "The previous version of this mold was restored.",
  ed_saving: "Saving...",
  ed_no_changes: "No changes yet.",
  ed_no_online_apps: "You have no apps online (ONLINE) to edit yet.",
  ed_no_vitrinas: "You don't have any Marketplace storefront yet.",
  ed_filtro_mis_apps: "My apps",
  ed_filtro_vitrinas: "Storefronts",
  ed_clon_activo_volver: "You have a change in progress on this app — tap to go back to its tab.",
  ed_clon_aviso: "Working on a copy — none of this is visible to your users yet.",
  ed_clon_sync: "Sync",
  ed_clon_apply: "Apply changes",
  ed_clon_discard: "Discard",
  ed_clon_espera_revision: "Wait for review to be enabled before applying.",
  ed_sync_error: "Couldn't sync.",
  ed_apply_error: "Couldn't apply the change.",
  ed_discard_error: "Couldn't discard.",
  ed_pick_app_to_see: "Pick an app above to see its live preview.",
  ed_visor_error: "Could not load this app's preview.",
  ed_cambios_aplicados: "Changes applied. Pick an app above to keep going — the same one or another.",
  ed_aplicando_en_curso: "Applying the changes to the real app...",
  ed_descartando_en_curso: "Discarding the working copy...",
  ed_cambios_descartados: "Changes discarded. Pick an app above to keep going — the same one or another.",
  ed_tab_chat: "Chat",
  ed_tab_visor: "Preview",
  ed_placeholder_no_app: ["Pick an app above to get started."],
  ed_credit: "credit",
  ed_credits: "credits",
  ed_tool_list: "Checked your app's pieces",
  ed_tool_read: "Read",
  ed_tool_kit: "Checked already-proven fixes",
  ed_tool_apply: "Applied a change to",
  ed_tool_image: "Generated a design image",
  ed_tool_video: "Generated a design video",
  ed_tool_failed: "failed",
  ed_fullscreen: "Full screen",
  ed_exit_fullscreen: "Back to normal screen",
  ed_see_more_apps: "See more apps",
  ed_back_to_apps: "Back",
  ed_model_label: "Model",
  ia_free_aviso_privacidad: "Meiti AI Free uses free-tier providers (Groq, NVIDIA and Gemini). What it generates may be reused to retrain MEITI's models, and those providers may use what they receive to improve theirs. If your app has private code or data, pick another model.",
  ed_spend_see_more: "See the detail in Credits",
  ed_undo: "Undo",
  ed_undone: "Undone",
  ac_title: "MEITI Content Assistant",
  ac_placeholder: "I can generate images, videos, and create and save records for whatever you need in the app.",
  ac_close: "Close",
  ac_discard: "Discard",
  ac_apply: "Apply",
  ac_applying: "Applying…",
  ac_applied: "Done. The changes are already in your app.",
  ac_discarded: "Discarded. Your app is unchanged.",
  ac_preview_loading: "Loading the preview…",
  ac_preview_empty: "Type your first request to get started.",
  ac_switch_description: "Creates sample data so your app stops looking empty, but it doesn't stop there: it also generates images and videos, and creates real records of whatever you need (customers, products, anything), several at a time. You speak in your own words, no code involved.",
  voz_start: "Dictate by voice",
  voz_stop: "Stop dictation",
  voz_error_permiso: "Couldn't turn on the microphone — check your browser's permission.",
  voz_error_contexto: "Voice dictation needs a secure connection (https). Testing over a local IP won't work — it will on meiti.dev.",
  voz_error: "Couldn't use voice dictation. Try again.",
  adj_tooltip: "Attach image or PDF",
  adj_quitar: "Remove attachment",
  adj_tipo_invalido: "That file type isn't allowed. Only images (JPG/PNG/WEBP) or PDF.",
  adj_demasiado_grande: "The file is too large (12MB max).",
  adj_error_lectura: "Couldn't read the file. Try again.",
  adj_sin_modelo_gratis: "Meiti AI Free doesn't support attachments. Switch to Haiku or Gemini Flash to attach something.",
  brk_dev_only: "Developer Plan only",
  brk_none_yet: "No premium bricks loaded yet.",
  lego_ex_trading: "A trading panel with live prices",
  lego_ex_stock: "A warehouse stock board",
  lego_ex_sensors: "A sensor panel for a plant",
  lego_ex_sales: "A summary of this month sales",
  lego_see_guide: "See the guide",
  lego_error_assistant: "The assistant failed.",
  lego_error_assemble: "Could not assemble the panel.",
  lego_ready: 'Your panel is ready. You will see it in "My apps".',
  lego_build_another: "Build another panel",
  lego_recent_panels: "The latest panels built",
  lego_chat_intro: "Tell me what panel you want to build. I look through the pieces that already work and suggest how to put it together.",
  lego_input_placeholder: "Build me a panel...",
  lego_yes_build: "Yes, build it like that",
  lego_build_free: "Build what is there (free)",
  lego_full_app: "Build the full app with AI",
  lego_adjust: "Adjust selection",
  lego_search_pieces: "Search more pieces by name...",
  mold_tag_base: "base",
  mold_tag_premium: "premium",
  mold_tag_forged: "forged",
  lego_panel_name: "Panel name",
  lego_page_count: "Number of pages",
  lego_style: "Style",
  lego_create_panel: "Create panel",
  mkd_error_stats: "Could not read your stats.",
  mkd_your_apps: "Your apps in the marketplace",
  mkd_active: "Active listings",
  mkd_sales: "Sales",
  mkd_commission: "MEITI commission taken",
  mkd_your_requests: "Your service requests",
  mkd_assigned: "Assigned (active)",
  mkd_completed: "Completed",
  mkd_your_milestones: "Your milestones",
  mkd_paid_out: "Paid out (released to you)",
  mkd_in_escrow: "In escrow (paid, not released)",
  mkd_monthly_income: "Committed monthly income",
  prv_render_failed: "This mold failed to render.",
  prv_clear: "Clear",

  aud_edited_by_hand: "You edited a mold in this app by hand from Dev Tools after the last check.",
  ed_reference_only: "Reference only. Load the code into the chat and ask Claude to adapt it.",
  ed_chat_placeholder: "Analyze this, build me a mold for..., add a filter to...",
  brk_locked_note: "These bricks exist (see the list below), but the code and cloning are for the Developer Plan.",
  lego_assign_pieces: "Pieces chosen. Assign them to a page:",
  lego_page_n: "Page 1",
  prv_paste_code: "Write or paste code in the Code tab to see the preview here.",
  prv_no_logs: "No logs yet. The mold console.log, warn and error will show up here.",

  dt_library_note: "Reusable bricks already proven in production. Same bar the AI uses when building: system base molds, or molds from apps already confirmed by human QA.",

  // --- Frases armadas (con variables) ---
  my_missing_pages: "It is missing {n} page(s) from the original plan. Not ready for real use yet.",
  my_confirm_remove: 'Remove "{app}" from your account? It is not deleted, it just stops showing up here. You can recover it later.',
  my_confirm_discard_page: 'Discard the page "{pagina}"? Nothing is charged, but it cannot be undone.',
  my_page_label: "Page: {pagina}",
  prof_seo_description_dyn: "{identidad} on MEITI: services, published apps and reviews from real clients.",
  aud_missing_credential: 'It declares an external connection to "{apis}" but there is no credential loaded for this app in API Connections.',
  aud_help_improve: "Help me improve this app code to raise these points. I will load or paste below the mold I want you to review.",
  dt_cloned_as: 'Cloned as "{nombre}". You already have it in "AI Editor", under "Your apps".',
  ed_code_loaded: 'Code loaded in "{molde}". The app will ask for QA confirmation again before offering itself as reusable.',
  ed_restored_named: 'The previous version of "{molde}" was restored.',
  ed_undo_named: 'Undo the last save in "{molde}"',
  lego_full_match: 'With these pieces I can build you a complete "{panel}": {piezas}. Shall we build it like that?',
  lego_partial_match: "With what I already have I can build you, for free: {piezas}. For the full idea what is missing is {falta}. That needs new code written and it is not free. Do we build what is there, or do we pass your request to the full AI builder?",
  lego_no_match: "I have no ready-made pieces for this (missing {falta}). Building this needs new code. Do we pass your request to the full AI builder?",
  lego_your_panel: "your panel",
  lego_something_missing: "something I do not have as a ready-made piece",
  lego_all_of_it: "everything you asked for",
  lego_page_num: "Page {n}",

  // --- Textos sueltos de interfaz ---
  credits_purchase_ok: "Done! Your purchase was credited.",
  credits_sub_ok: "Done! Your subscription is active.",
  credits_payment_cancelled_balance: "You cancelled the payment. Your balance did not change.",
  credits_plans_coming: "Monthly plans are still being set up. In the meantime you can keep using single credits.",
  tools_free_note: "Library, Pentagon audit and Marketplace are free for any registered dev:",
  tools_dev_plan_note: "AI Editor and Lego Panel are part of the Developer Plan subscription.",
  wiz_login_gift: "Sign in with your email and we give you {n} free credits. No forms to fill: we send you a code and that is it. Your app stays as it is, you continue from here.",
  wiz_signin_gift: "Sign in and get {n} free credits",
  wiz_keep_as_is: "Keep it as is",
  wiz_setup_later: "Set this up later",
  purchase_cancelled: "You cancelled the purchase. You were not charged.",
  market_no_listings: "No listings in this category.",
  trial_7_days: "7 days of the Developer Plan, free",
  trial_pitch: "Credits to keep building and access to Tools, no card needed. Just complete your dev profile.",
  svc_dev_unavailable: "That developer is not available right now. Pick another one to continue with your request.",
  svc_no_devs: "No developers have set up a profile yet. Try again later.",
  svc_dev_notified: "We let the developer know about your request. They need to confirm whether they take it.",
  svc_dev_timeout: "If they do not answer in time, the request goes back to available on its own and we show you another match.",
  svc_retainer_note: "A recurring monthly payment to a dev you already work with. No escrow: they get paid directly every month.",
  svc_retainer_active: "Retainer active!",
  svc_none_yet: "You do not have any yet.",
  svc_see_my_profile: "See my public profile →",
  svc_payouts_ready: "You can get paid now. Account is set up.",
  svc_start_retainer: "Start retainer",
  aud_intro: "Pick one of your apps and run the same scoring engine the MEITI autonomous review already uses. Free, and it does not call any AI.",
  brk_intro: "Premium bricks, hand-built by the MEITI team and exclusive to the Developer Plan. They are not available anywhere else.",

  my_pages_bundled: "Since your request includes new screens ({n}), we generate them together with the last one you create, so everything works at once instead of leaving you buttons that lead to a screen that does not exist yet.",
  my_building_copy: "We are building a copy of your app to test the change. The one already online keeps working normally in the meantime.",
  ind_app_coming_note: 'We are building it and a team member will review it before activating it. You will find it in "My apps" as soon as it is ready. The next step, packaging it for your Raspberry Pi, is still manual: we will get in touch.',
  ind_scanner_note: "Download the scanner, run it on a machine connected to your equipment (or directly on the Raspberry Pi) and it will upload the result on its own. If that network has no internet access, copy the perfil.json file it leaves and upload it below by hand.",
  ind_wiring_plan: "This is the wiring plan: which pin controls or reads each thing, and what extra hardware is needed.",
  tools_free_access_note: "You are seeing the free tools because you have a dev profile. AI Editor and Lego Panel are part of the Developer Plan subscription.",
  tools_architect_access: "Access granted by architect exception. There is no active Developer Plan subscription on this account.",

  my_discard_anyway: "{error}\n\n{lista}\n\nDiscard it anyway?",
  my_extra_per_page: " + {n} credits for each of the other new pages, when you generate them (the first one is already included)",
  svc_days: "{n} days",
  aud_points_found: "Points it found:",
  lego_can_reuse: "(you can already reuse: {piezas})",
  my_waiting_no_credits: "It is waiting because you did not have enough credits.",

  aud_result: 'The Pentagon audit of "{app}" gave an average of {promedio} (baseline {base})',
  aud_would_not_pass_suffix: ", it would not pass",
  ed_this_is_code: 'This is the code for "{molde}":',
  lego_suggestion: "Suggestion based on your request. Adjust if needed ({n} / {max}):",

  sup_title: "MEITI Support",
  sup_need_support: "I need support",
  sup_new_report: "New report",
  sup_other_app: "Another app, or I would rather explain it myself",
  sup_create_my_app: "Create my app",
  sup_architect: "MEITI Architect",
  profile_rather_dev: "I would rather sign up as a dev →",
  aud_pick_app: "-- Pick an app --",
  aud_baseline: "Baseline:",
  aud_previous_stable: "previous stable versions",
  aud_average: "Average",
  aud_check_with_claude: "Check with AI Editor",
  dt_clone: "Clone",
  dt_view: "View",
  ed_load_into_mold: "Load code into the mold:",
  prv_console: "Console",
  prv_sample_note: "Preview with sample data. It is never real: it is there to see the shape of the mold (table, form, etc.).",
  tools_see_more: "More tools",
  ind_hardware_pending: 'There is hardware still unconfirmed and our team is reviewing it. "Build the app" unlocks only when it is ready.',
  ind_generate_app: "Build the app",
  ind_download_scanner: "Download scanner",
  ind_project_ref: "Project reference:",
  retry_keep_progress: "Retry (without losing your work)",
  ind_login_note: "The downloadable scanner carries a credential tied to your account. We send you a code, no passwords.",
  wiz_continue: "Continue",
  wiz_can_close: "You can close this window, no need to wait here. We are building it and a team member will review it before activating it.",
  wiz_reference: "Reference:",
  wiz_asking_permission: "Asking for permission...",
  wiz_we_will_notify: "We will let you know",
  wiz_we_will_email: "We will write to you at",
  wiz_create_another: "Create another app",
  market_nothing_yet: 'Nothing published yet. Be the first from "My apps".',
  market_new_badge: "New",
  market_sold: "sold",
  market_see_demo: "Watch demo video",
  my_ai_assistant: "AI assistant",
  my_download: "Download",
  my_dev_plan_active: "Developer Plan active: you pay a tiered commission based on how much you sell this month, not a flat 30%.",
  trial_to_activate: "to activate your free Developer Plan trial.",
  login_other_email: "Use another email",
  prof_trust_score: "Trust Score:",
  prof_completed_contracts: "completed contracts",
  prof_tell_project_link: "Tell me about your project →",
  prof_delivery_days: "days to deliver",
  svc_payment_held: 'Payment held successfully! When the dev delivers that milestone, hit "Approve" to release it.',
  svc_estimated_budget: "Estimated budget:",
  svc_pick_other_dev: "Pick another developer",
  svc_see_full_profile: "See full profile →",
  svc_add_milestone: "+ Add another milestone",
  svc_start_new_request: "Start a new request",
  svc_paid: "Paid",
  svc_bio: "Bio",
  svc_share_preview: "How your profile looks when shared",
  svc_share_preview_hint: "(optional, like the title and description of a YouTube video)",
  svc_available_projects: "Available for new projects",
  svc_accepts_retainers: "I take monthly retainers from companies",
  showcase_more_devs: "More devs",
  showcase_deliveries: "deliveries",
  chat_tags: "Tags",
  chat_close_help: "Close help",

  prof_services_link: "Services → I offer services",
  prof_your_public_view: "You are seeing your public profile the way a visitor sees it. To edit it, go to",
  trial_sign_in_at: "Sign in at",
  wiz_signin_to_see: 'Sign in with your email in "My apps" to see it as soon as it is ready.',
  svc_complexity_sep: "· Complexity:",

  svc_complexity: "Complexity",

  lego_page_word: "Page",
  mkd_milestones_word: "milestones",
  mkd_retainers_word: "retainers",

  wiz_advanced_note: 'You chose the Advanced level. To make a "pro" app clear, we will ask you several extra questions.',
  wiz_level_too_small: 'Your request needs more pages than the "{actual}" level covers. Move up to "{sugerido}" to build the full app, or trim the request below.',
  wiz_level_cheaper_note: 'Your request fits in the "{sugerido}" level, which costs fewer credits than the "{elegido}" you picked. You can move down and pay less, or keep it as is if you want room to grow it later.',
  wiz_use_level_cheaper: "Use {nivel} level and pay less",
  wiz_resend_why: "Since each person signs in with their own account, we need to send access codes by email from YOUR own Resend account, not MEITI’s.",
  wiz_resend_step1: "Go to",
  wiz_resend_step2: ", create a free account and generate an API key. Then paste it below. We never show it to anyone or write it into your app code.",

  my_assistant_for: "Assistant · {titulo}",
  my_n_screens: "{n} screen(s)",
  my_build_failed: "failed: {motivo}",
  my_unknown_error: "unknown error",
  my_copied_from: 'Originally copied from "{molde}". That mold has since changed.',
  my_wait_before_apply: "Still being reviewed. Wait before applying.",
  my_removed_apps: "Apps you removed ({n})",
  my_request_change_for: 'Request a change · "{app}"',
  my_new_pages: "New pages ({n})",
  my_new_functions: "New features ({n})",
  my_function_where: "in {donde}",
  my_change_cost: "This change costs {n} credits.",
  my_will_create_copy: "We will create a copy of your app to test this change. The one already online keeps working normally for your users while it is tested.",
  my_others_can_buy: 'Other users will be able to buy a copy of "{app}".',
  my_change_in_progress: 'Change in progress: "{app}"',
  my_mold_updates: "Mold updates available ({n})",
  my_pending_pages: "Pending pages ({n})",
  my_installer_for: "{plataforma} installer:",
  my_request_failed_credit: "A request failed on our side. The credit ({costo}) is held until you retry or cancel it.",

  ed_overwrite_confirm: 'Overwrite "{molde}" with this code?',
  prof_n_reviews: "{n} reviews",
  svc_match_score: "match {n}",
  tools_trial_until: "Free trial, expires on",
  wiz_page_plan: "Page plan ({n})",
  market_purchase_copied: "Done! Your purchase was copied to",
  trial_activated: "Trial activated. We credited you",
  prv_live_error: "[ LIVE ERROR ]:",

  ed_your_apps: "Your apps ({n})",
  ed_library: "Library ({n})",
  lego_continue: "Continue ({n})",
  ind_role: "Role",

  svc_portfolio_placeholder: "https://myportfolio.com\nhttps://github.com/myusername",

  dt_no_code: "(no code: this mold is not REACT_FORJADO)",
  ed_chat_intro: "Ask it to analyze, create or modify a mold. Load one from the left or paste code directly.",
  lego_no_clear_match: "We did not find a clear suggestion. Search manually for the pieces you need:",
  ind_scan_received: "Scan received",
  ind_awaiting_scan: "Waiting for scan",
  ind_upload_manual: "Upload perfil.json by hand",
  my_industrial_project: "Industrial project",
  my_build_installer_tip: "Compile a native installer (Windows, Linux or Android)",
  my_publish_tip: "Publish this app to the marketplace so others can buy it",
  my_publish_menu_tip: "Publish this app: to the MEITI Marketplace, or generate the Play Store package",
  my_publish_where: "Publish to",
  my_publish_option_marketplace: "Meiti Marketplace",
  my_publish_option_playstore: "Google Play Store",
  my_publish_option_playstore_tip: "Generates the signed (.aab) package, ready to upload to Play Store by hand",
  my_publish_option_domain: "Own Domain",
  my_publish_option_domain_tip: "Not available yet",
  my_request_change_tip: "Ask for something to be added or changed in this app",
  my_build_queued: "queued: another build is running, wait a few minutes.",
  my_build_done: "done ✓",
  my_waiting_generate: "waiting for you to generate it",
  my_in_review: "in review",
  my_nothing_to_test: "Nothing new to test yet. Generate the pending screen and the full change applies there.",
  my_sync_when_applied: "Sync once the change is applied. For now this copy is identical to your app.",
  my_bring_real_data: "Bring in the real data that came into the original app while this change was being reviewed",
  svc_pay_escrow: "Pay (held in escrow)",
  svc_verify_email_note: "To assign a dev or release a payment we need to verify your email. No passwords, and it keeps spam out.",
  svc_save_profile: "Save profile",
  svc_configure: "Set up",
  svc_opening: "Opening...",
  svc_add_package: "Add package",

  my_export_tip: "Download as a standalone project, with its own backend",
  my_installer_shared_note: "This app is shared: it lives on a server and every device opens its address. A desktop installer would keep separate data on each machine, so it is not offered.",
  my_admin_access: "Admin access",
  my_admin_access_tip: "Code and steps to sign in as admin in the exported app",
  my_admin_access_none: "This app has no staff or admin pages: once exported, whoever runs it is its owner and needs no code.",
  my_admin_access_email: "Admin: {email}",
  my_admin_access_code: "Admin code",
  my_admin_access_code_note: "Keep it like a password. It signs you in as admin even if email stops working.",
  my_admin_access_copy: "Copy",
  my_admin_access_copied: "Copied",
  my_admin_access_steps: "How to sign in",
  my_admin_access_resend: "Resend instructions to my email",
  my_admin_access_sent: "Instructions sent to {email}.",
  my_admin_access_error: "Could not load the admin access.",

  ed_open_with_claude: "Open with Claude",
  ed_back_to_molds: "Back to molds",

  ed_talk_to_claude: "Talk to Claude",

  // ——— SEO / browser chrome ———
  seo_title: 'Build an app with AI, no coding | MEITI',
  seo_description: 'Tell us what app you need, in your own words. We build it with AI, no code. Start free.',

  // ——— Landing ———
  hero_title: 'Build your app with AI. No coding.',
  hero_subtitle: 'Describe the app you need. We design it, test it, and hand it over ready to use.',
  hero_help: "Not sure where to start? Tell us what it's for and who's going to use it. That's enough.",
  hero_guide_link: 'See the request guide',

  // ——— Landing examples (they fill the input when tapped) ———
  example_tasks: "Today's to-do list",
  example_habits: 'Daily habit tracker',
  example_journal: 'Personal journal with mood tracking',
  example_expenses: 'Monthly expense tracker',
  example_irrigation: 'Automate greenhouse irrigation',

  // ——— Conversation ———
  chat_intro: "Tell me what app you need. A couple of quick questions and we'll build it.",
  chat_placeholder: 'Type your answer...',
  chat_reintentar: 'Retry',
  mode_to_dark: 'Switch to dark mode',
  mode_to_light: 'Switch to light mode',
  style_pack_label: 'How the screen is laid out',
  // 💬 [SUGERENCIAS DENTRO DEL CAMPO 2026-08-26] See es.js — same list, same order.
  chat_sug_crear: [
    'Tell me what app you need and we build it.',
    'Say what it is for and who will use it.',
    'Try: "an expense tracker for my business".',
    'Not sure where to start? Tap an idea above.'
  ],
  chat_sug_soporte: [
    'Tell me what happened, with any detail you have.',
    'Say which screen it was on and what you expected.',
    'If it is a charge, send the date and the amount.'
  ],
  chat_sug_cambio: [
    'Tell me what to add, change or remove.',
    'Name the screen and what it is missing.',
    'Try: "on Clients, add a search box".',
    'If something is broken, say what you did and what you saw.'
  ],
  chat_sug_lego: [
    'Tell me what panel you want to build.',
    'Say what data it handles and who enters it.',
    'Try: "a task board with statuses".'
  ],
  chat_sug_editor: [
    'Ask it to analyze, create or modify a mold.',
    'It can read and edit the app\'s molds on its own.',
    'Try: "review this mold and tell me what is wrong".'
  ],
  chat_sug_industrial: [
    'Tell me what machine you want to automate.',
    'Say which sensors or motors it has.',
    'Try: "turn on a pump when the level drops".'
  ],
  chat_sug_servicios: [
    'Tell us what you need and we prepare the request.',
    'Say when you need it by.',
    'The more specific, the better the dev can quote it.'
  ],
  chat_charla_en_proceso: 'You have an unfinished chat.',
  chat_continuar_charla: 'Continue',
  chat_empezar_de_nuevo: 'Start over',

  // ——— Request review ———
  review_title: 'Review your request',
  review_anything_else: 'Anything to add or fix?',
  review_anything_else_optional: 'Anything to add or fix? (optional)',

  // ——— Style ———
  style_title: 'Pick a style for your app',
  style_subtitle: 'You can always change it later.',
  style_minimal: 'Minimal',
  style_warm: 'Warm',
  style_dark: 'Elegant dark',
  style_colorful: 'Colorful',
  style_professional: 'Professional',

  // ——— Complexity level ———
  level_basic: 'Basic',
  level_basic_desc: '1-2 screens, just what you need to start using it right away.',
  level_complete: 'Complete',
  level_complete_desc: 'Several screens, forms and settings. A real app for everyday use.',
  level_advanced: 'Advanced',
  level_advanced_desc: 'The most complete version, with more features and detail.',

  // ——— Credits and payment ———
  credits_added: "Credits added! You're good to go.",
  credits_payment_cancelled: "Payment cancelled. You weren't charged.",
  credits_missing_title: "You're short on credits",
  credits_buy: 'Buy Credits',

  // ——— Done ———
  done_title: 'We got your request!',
  done_email_optional: 'or leave your email (optional)',

  // ——— Errors ———
  email_api_key_placeholder: 'Your Resend API key',

  error_generic: 'Something went wrong',
  error_payment_start: "Couldn't start the credit payment.",
  error_assistant_silent: "The assistant didn't respond.",
  error_assistant_connection: 'Connection to the assistant failed.',
  error_not_enough_credits: "You don't have enough credits to build this app.",
  error_notice_failed: 'Couldn\'t turn on the notification. You can still check in "My apps".'
};
