// 🌎 [MULTILENGUAJE 2026-08-21] Español — el idioma natural de MEITI.
//
// Este archivo es el original, no una traducción: acá se escribe la voz del producto.
//
// LA VOZ, definida por el usuario (2026-08-21): **latino neutro, con "tú"**. NO voseo.
//   ✅ "Crea tu app", "Ya puedes seguir", "Revisa tu pedido"
//   ❌ "Creá tu app", "Ya podés seguir", "Revisá tu pedido"
// Plana, sin modismos de ningún país. Motivo comercial además del gusto: el voseo suena
// específicamente rioplatense, y los visitantes que llegan por anuncios son de México. El neutro
// le habla igual a México, Colombia, Perú y Centroamérica.
//
// FRASES CORTAS: dos oraciones breves pegan más que una larga con guiones.
//
// ABREVIATURAS EN INGLÉS a propósito — "IA", "app". Son universales, la gente ya las conoce y
// acortan la frase. "Inteligencia artificial" ocupa tres veces más y no dice nada extra.
//
// ⚠️ Las claves están en INGLÉS y no se traducen nunca — son nombres, no texto.
// ⚠️ Lo que NO va acá: los prompts de la IA. Esas son instrucciones para Gemini, viven en el
//    código y se quedan en español (ej. el bloque de NIVELES en LandingWizard ~L120).

export default {
  // ——— Navegación (sale en todas las pantallas) ———
  nav_my_apps: 'Mis apps',
  nav_create_app: 'Crear app',
  nav_credits: 'Créditos',
  nav_tools: 'Herramientas',
  nav_marketplace: 'Marketplace',
  nav_services: 'Servicios',
  nav_guides: "Ayuda",
  nav_lego_panel: 'Lego Panel',

  // ——— Compartidos (chat, soporte, sesión) ———
  chat_input_placeholder: 'Créame una app...',
  chat_more_examples: 'Ver más ejemplos',
  chat_help_aria: '¿No sabes cómo empezar?',
  send: 'Enviar',
  see_more: 'Ver más',
  see_my_apps: 'Ver mis apps',
  support: 'Soporte',
  sign_in: 'Entrar',
  free_credits_badge: '{n} créditos gratis',

  menu_expand: 'Expandir menú',
  menu_collapse: 'Colapsar menú',
  menu_close: 'Cerrar menú',
  menu_open: 'Abrir menú',
  description: 'Descripción',

  // ——— Marketplace ———
  market_page_description: 'Apps ya hechas por otros usuarios, listas para usar. Al comprar, se copia entera a tu cuenta.',
  market_seo_title: 'Marketplace de apps hechas con IA | MEITI',
  market_seo_description: 'Apps ya creadas por otros usuarios con MEITI, listas para usar. La compras y se copia entera a tu cuenta al instante.',
  market_error_load: 'No se pudo consultar el marketplace. Prueba de nuevo en un rato.',
  market_error_buy: 'No se pudo iniciar la compra.',
  sort_recent: 'Recientes',
  sort_top_rated: 'Mejor calificadas',
  sort_best_selling: 'Más vendidas',
  market_milestone_tooltip: 'Marcada por el equipo de MEITI como ejemplo de buena práctica (Hito de evolución del Pentágono)',
  market_score_tooltip: 'Puntaje automático del Pentágono de MEITI. Mide calidad de código, no la opinión de compradores.',
  market_rating_tooltip: 'Calificación de compradores reales',
  hide_description: 'Ocultar descripción',
  show_description: 'Ver descripción',
  cancel: 'Cancelar',
  market_rate_prompt: '¿Ya la compraste? Califícala',
  market_pick_stars: 'Elige de 1 a 5 estrellas.',
  market_error_rating: 'No se pudo enviar la calificación.',
  sending: 'Enviando...',
  market_send_rating: 'Enviar calificación',

  // ——— Créditos y planes ———
  credits_current_balance: 'Saldo actual',
  credits_monthly_plans: 'Planes mensuales',
  opening: 'Abriendo...',
  credits_manage_plan: 'Gestionar plan',
  credits_payment_failed: 'Tu último pago falló. Actualiza tu método de pago desde "Gestionar plan" para no perder la renovación.',
  per_month: '/mes',
  redirecting: 'Redirigiendo...',
  credits_subscribe: 'Suscribirme',
  credits_per_month: '{n} créditos cada mes',
  credits_apps_per_month: 'hasta {n} apps avanzadas al mes',
  credits_auto_renew: 'se renueva solo, con un mes de respaldo si no lo gastas todo',
  credits_cheaper: '{n}% más barato que comprar créditos sueltos',
  credits_unit: 'créditos',
  credits_no_movements: 'Todavía no hay movimientos.',
  credits_seo_title: 'Créditos | MEITI',
  credits_error_balance: 'No se pudo consultar tu saldo. Prueba de nuevo en un rato.',
  credits_error_payment: 'No se pudo iniciar el pago.',
  credits_error_subscription: 'No se pudo iniciar la suscripción.',
  credits_error_plan: 'No se pudo abrir la gestión de plan.',
  credits_sign_in_plan: 'Inicia sesión (desde "Mis apps") para gestionar tu plan.',
  credits_page_description: 'Cada app nueva consume créditos según su nivel de complejidad.',
  credits_browser_balance: 'Saldo de este navegador. Inicia sesión (desde "Mis apps") para ver el total de tu cuenta.',
  credits_redirecting: 'Redirigiendo a pago...',
  credits_cost_by_level: 'Costo por nivel de app',
  credits_current_plan: 'Tu plan actual',
  coming_soon: 'Próximamente',
  credits_usage: 'Uso de créditos',
  credits_history: 'Historial de movimientos',
  // 🌐 Idiomas de una app generada (ModalIdiomas en MisApps.jsx)
  lang_button: 'Idiomas',
  lang_title: 'Idiomas de "{app}"',
  lang_intro: 'Tu app está escrita en un idioma. Agregarle otro no reescribe nada: se traducen sus textos y quien la use la ve en el suyo.',
  lang_current: 'Ya la habla',
  lang_pick: 'Elige hasta {tope} para agregar ahora',
  lang_cost: '{n} crédito por idioma. Si alguno falla, ese crédito se devuelve.',
  lang_add: 'Agregar {n} idioma(s)',
  lang_working: 'Traduciendo...',
  lang_retry: 'Reintentar',
  lang_done_ok: '{n} textos traducidos',
  lang_done_partial: '{n} traducidos, {faltan} quedaron en el idioma original',
  lang_failed: 'No se pudo. El crédito se devolvió.',
  lang_none_yet: 'Esta app todavía no tiene textos preparados para traducir. Las que se crean desde ahora nacen listas.',
  lang_close: 'Cerrar',
  // 🪟 La vidriera del marketplace (MisApps.jsx)
  my_published_badge: 'Publicada',
  my_view_storefront: 'Ver',
  my_publish_already: 'Esta app ya está publicada. Con \"Publicar cambios\" actualizas lo que se muestra en la tienda.',
  trial_chat: 'Preguntar',
  trial_chat_tip: 'Habla directo con quien hizo esta app. Te responde desde su soporte.',
  trial_chat_title_buyer: 'Pregúntale a quien la hizo',
  trial_chat_title_seller: 'Alguien está probando tu app',
  trial_chat_greet_buyer: 'Escríbele a quien hizo esta app. Puedes preguntarle si sirve para lo que necesitas, si se le puede cambiar algo, o lo que quieras saber antes de comprarla.',
  trial_chat_greet_seller: 'Alguien está probando tu app ahora mismo. Lo que le respondas puede ser la diferencia entre que la compre o que se le venza la prueba.',
  trial_chat_placeholder: 'Escribe tu mensaje',
  trial_chat_error: 'No se pudo enviar el mensaje.',
  trial_state_live: 'Probándola ahora',
  trial_state_bought: 'La compró',
  trial_state_over: 'Se le venció',
  seller_support: 'Soporte',
  seller_support_tip: 'Las conversaciones de quienes están probando tus apps',
  seller_support_title: 'Soporte de tu tienda',
  seller_support_sub: 'Quienes están probando tus apps y te escribieron',
  seller_support_empty: 'Todavía nadie te escribió. Cuando alguien pruebe una de tus apps y tenga una pregunta, aparece acá.',
  seller_support_count: '{n} mensaje(s)',
  seller_support_error: 'No se pudo cargar tu soporte.',
  ago_now: 'recién',
  ago_minutes: 'hace {m} min',
  ago_hours: 'hace {h} h',
  ago_days: 'hace {d} día(s)',
  cat_trial: 'App de Prueba',
  my_style: 'Estilo',
  my_style_tip: 'Cambia el estilo visual de esta app. Es instantáneo y no reforja nada.',
  trial_session: 'Sesión de prueba',
  trial_error: 'No se pudo empezar la prueba.',
  market_own_view: 'Ver',
  error_servidor_no_responde: 'El servidor no respondió. Recarga la página y prueba de nuevo.',
  my_error_open_storefront: 'No se pudo abrir tu vidriera.',
  market_error_open: 'No se pudo abrir tu vidriera.',
  market_own_tip: 'Esta app es tuya. Abre tu vidriera desde Mis apps para lucirla.',
  trial_left_hours: 'Te quedan {h} h {m} min',
  trial_left_minutes: 'Te quedan {m} min',
  trial_over: 'La prueba terminó',
  trial_language_free: 'Agrégale un idioma, gratis. Es uno por prueba.',
  trial_language_free_short: 'Idioma gratis',
  trial_language_spent: 'Ya usaste el idioma gratis de esta prueba. Al comprarla puedes agregarle los que quieras.',
  trial_language_spent_short: 'Idioma usado',
  trial_buy: 'Comprar ${precio}',
  trial_start: 'Probar gratis',
  trial_start_tip: 'Te damos una copia tuya por 2 horas: ábrela, úsala, cámbiale el estilo y llévatela al teléfono. Si te gusta, la compras.',
  trial_login_needed: 'Este navegador ya tiene una cuenta. Inicia sesión para probar la app.',
  qr_title: 'Ábrela en tu teléfono',
  qr_help: 'Escanea el código con la cámara del teléfono. La app se abre a pantalla completa, sin instalar nada.',
  qr_button: 'QR',
  qr_tip: 'Código para abrir la app en tu teléfono',
  qr_copy_link: 'Copiar el link',
  qr_copied: 'Copiado',
  qr_temporary: 'Este link vale unos minutos. Si se vence, vuelve a abrir el QR.',
  qr_error: 'No se pudo generar el código.',
  my_republish: 'Publicar cambios',
  my_edit_listing: 'Editar ficha',
  my_edit_listing_tip: 'Cambia el título, la descripción, la categoría, el video o el precio de lo que muestra la tienda, o quítala de la tienda.',
  my_edit_listing_title: 'Editar la ficha de la tienda',
  my_edit_listing_note: 'Los cambios se ven en la tienda al instante. Para actualizar la app en sí, usa "Publicar cambios".',
  my_loading_listing: 'Cargando la ficha...',
  my_save_changes: 'Guardar cambios',
  my_saving: 'Guardando...',
  my_error_edit_listing: 'No se pudieron guardar los cambios.',
  my_category_missing: 'Categoría anterior (ya no existe)',
  my_unpublish: 'Quitar de la tienda',
  my_unpublish_note: 'Deja de mostrarse y de venderse. Quien ya la compró la conserva, y puedes volver a publicarla cuando quieras.',
  my_unpublish_confirm: 'Sí, quitarla',
  my_unpublishing: 'Quitando...',
  my_error_unpublish: 'No se pudo quitar de la tienda.',
  my_republish_tip: 'Reemplaza lo que se muestra en la tienda por una copia nueva de tu app. Los ejemplos que cargaste en la vidriera se pierden.',
  my_confirm_republish: 'Se va a reemplazar lo publicado por una copia nueva de tu app.\n\nLos datos de ejemplo que cargaste en la vidriera NO viajan: la copia nueva nace vacía y los tendrás que volver a cargar con "Ver".\n\n¿Continuar?',
  my_error_republish: 'No se pudieron publicar los cambios.',
  my_view_storefront_tip: 'Abre la copia que ve tu comprador. Lo que cargues acá son los datos de ejemplo que verá quien la pruebe.',
  credits_spend: 'Gasto de créditos',
  credits_movement: 'Movimiento de créditos',
  plan_basic: 'Básico',
  plan_mid: 'Medio',
  plan_advanced: 'Avanzado',

  // --- Guias ---
  guide_page_description: "Para no ir adivinando: cómo funciona el Wizard y cómo sacarle el jugo.",
  guide_sec_wizard_title: "Cómo funciona el Wizard, paso a paso",
  guide_sec_wizard_subtitle: "Los 8 pasos desde que abres MEITI hasta que tu app está lista.",
  guide_sec_ai_title: "Cómo piensa la IA (y por qué importan tus palabras)",
  guide_sec_ai_subtitle: "Antes de escribir tu pedido, vale entender con qué estás hablando.",
  guide_sec_checklist_title: "Qué tener en cuenta para armar tu pedido en MEITI",
  guide_sec_checklist_subtitle: "Un checklist corto. Si tocas estos cinco puntos, ya vas por buen camino.",
  guide_sec_tips_title: "Cómo escribir un buen pedido",
  guide_sec_tips_subtitle: "Cinco tips para que la IA entienda bien qué quieres desde el primer mensaje.",
  guide_sec_market_title: "Vender plantillas ya hechas",
  guide_sec_market_subtitle: "Marketplace: convertir una app tuya en un producto que otros compran.",
  guide_sec_services_title: "Ofrecer servicios a medida",
  guide_sec_services_subtitle: "Servicios: trabajar directo con clientes, con pago protegido por hitos.",
  guide_sec_devtips_title: "Prompting pensado para vender",
  guide_sec_devtips_subtitle: 'Los mismos tips de la pestaña "Para ti" aplican. Estos son extra.',
  guide_wizard_1_title: "1. Idioma",
  guide_wizard_1_text: "Eliges en qué idioma va a estar tu app: textos, botones, todo.",
  guide_wizard_2_title: "2. ¿Para quién es?",
  guide_wizard_2_text: "Uso personal o para una empresa o equipo. Esto solo agrupa tus apps en el sistema, no cambia lo que la app puede hacer.",
  guide_wizard_3_title: "3. Nivel de la app",
  guide_wizard_3_text: "Básica (1-2 pantallas, lo esencial), Completa (uso diario real) o Avanzada (la versión más completa posible). Cada nivel cuesta más o menos créditos, y le dice a la IA cuánto construir.",
  guide_wizard_4_title: "4. Cuenta qué quieres",
  guide_wizard_4_text: "Escribes en tus palabras qué necesitas. Cuanto más concreto, mejor arranca. Más abajo hay tips.",
  guide_wizard_5_title: "5. Preguntas cortas",
  guide_wizard_5_text: "Te preguntamos lo que falta: qué datos vas a guardar, si necesitas conectar algo externo, si va a haber varias personas con su propia cuenta.",
  guide_wizard_6_title: "6. Estilo visual",
  guide_wizard_6_text: "Eliges una paleta de colores de una lista curada.",
  guide_wizard_7_title: "7. Creación y revisión",
  guide_wizard_7_text: "Gemini escribe el código, un chequeo automático (el Pentágono) lo revisa y hasta prueba la app haciendo clic de verdad antes de aprobarla. Te avisamos cuando está lista.",
  guide_wizard_8_title: '8. Ya está en "Mis apps"',
  guide_wizard_8_text: "Si algo no te cierra, se lo puedes pedir directo desde ahí. No hace falta arrancar de cero.",
  guide_ai_1_title: "No lee tu mente",
  guide_ai_1_text: "La IA solo sabe lo que escribiste en el mensaje, no lo que te imaginas en la cabeza. Si no lo escribiste, para ella no existe.",
  guide_ai_2_title: "Completa huecos con su propio criterio",
  guide_ai_2_text: "Todo lo que no aclaraste lo decide ella sola. A veces acierta, a veces no. Cuanto más completes tú, menos tiene que adivinar.",
  guide_ai_3_title: "Funciona por parecido, no por magia",
  guide_ai_3_text: 'Predice qué construir comparando tu pedido con millones de ejemplos parecidos que ya vio. Un pedido más específico se parece más a "una app real" y menos a una idea suelta.',
  guide_ai_4_title: "No capta el tono ni lo que no dijiste",
  guide_ai_4_text: 'No es una persona: no interpreta un "algo así como..." ni lee entre líneas. Lo que no está escrito de forma clara, no se tiene en cuenta.',
  guide_checklist_1_title: "Qué datos vas a guardar",
  guide_checklist_1_text: 'Los "campos" de cada cosa que la app maneja. Por ejemplo, en una tarea: título, fecha límite, si está hecha.',
  guide_checklist_2_title: "Qué vas a hacer con esos datos",
  guide_checklist_2_text: "Ver, agregar, editar, borrar, buscar, filtrar. Nómbralas, no las des por sentado.",
  guide_checklist_3_title: "Quién la va a usar",
  guide_checklist_3_text: "Solo tú, o varias personas cada una con su propia cuenta.",
  guide_checklist_4_title: "Si necesita traer algo de afuera",
  guide_checklist_4_text: "Clima, un mapa, otra IA. Nómbralo aunque no tengas la clave todavía.",
  guide_checklist_5_title: "Qué tan grande la quieres",
  guide_checklist_5_text: "Eso ya lo eliges con el nivel Básica, Completa o Avanzada del paso 3. No hace falta repetirlo en el texto.",
  guide_tips_1_title: "Sé concreto sobre QUÉ vas a guardar",
  guide_tips_1_text: '"Una lista de tareas" es vago. "Tareas con título, fecha límite y si están hechas o no" ya le da forma real a la app.',
  guide_tips_2_title: "Nombra las acciones que necesitas",
  guide_tips_2_text: "Ver, agregar, editar, borrar. Si no las mencionas, la app arranca solo con lo básico.",
  guide_tips_3_title: "¿Necesitas traer datos de otro servicio?",
  guide_tips_3_text: 'Dilo, por ejemplo "quiero ver el clima real". MEITI te arma un campo de Configuración para que cargues tu propia clave DESPUÉS. No hace falta tenerla en este momento.',
  guide_tips_4_title: "¿Varias personas, cada una con su cuenta?",
  guide_tips_4_text: "Dilo y se arma el login solo, con código por email. Tú no programas nada de eso.",
  guide_tips_5_title: "No tiene que salir perfecta a la primera",
  guide_tips_5_text: 'Una vez creada, le puedes seguir pidiendo cambios desde "Mis apps".',
  guide_market_1_title: "Publicar una plantilla ya hecha",
  guide_market_1_text: "Eliges una app tuya que ya esté ONLINE y aprobada. Piso de calidad: tiene que tener un puntaje estable del Pentágono de 75 o más, el mismo piso que ya exige la aprobación normal.",
  guide_market_2_title: "Split de ingresos",
  guide_market_2_text: "70% para ti, 30% para la plataforma por cada venta. El Plan Developer, que es una suscripción aparte, baja ese porcentaje según tu volumen.",
  guide_market_3_title: "Qué pasa al comprarla",
  guide_market_3_text: "Se clona completa para el comprador. Tú sigues siendo dueño del original y puedes seguir vendiéndola.",
  guide_services_1_title: "Arma tu perfil",
  guide_services_1_text: 'Portfolio y si aceptas retainers, desde tu panel de dev en "Servicios".',
  guide_services_2_title: "Matching automático",
  guide_services_2_text: "El cliente arma su brief charlando con la IA y el sistema te sugiere como match según lo que ofreces.",
  guide_services_3_title: "Escrow por hitos",
  guide_services_3_text: "El pago del cliente queda en custodia y se libera hito por hito, cuando el cliente aprueba cada uno. Nunca cobras por adelantado sin entregar.",
  guide_services_4_title: "Paquetes a precio fijo",
  guide_services_4_text: "También puedes vender paquetes de servicio con precio cerrado, sin pasar por el brief ni la negociación.",
  guide_services_5_title: "Tu reputación se arma sola",
  guide_services_5_text: "El trust score y el badge (Estándar, Verificado o Elite) se calculan del historial real de ventas y reseñas. Nunca se pueden inflar a mano, ni siquiera tú mismo.",
  guide_devtips_1_title: "Piensa en alguien que la usa sin ti al lado",
  guide_devtips_1_text: "Si vas a publicarla, sé más explícito con validaciones y estados vacíos, o sea qué se ve cuando todavía no hay datos cargados. Quien la compre no te va a poder preguntar.",
  guide_devtips_2_title: "Nivel Avanzado si es para vender",
  guide_devtips_2_text: 'Así entra todo lo que un comprador esperaría de una app "pro": filtros, historial, estadísticas.',
  guide_devtips_3_title: "Reusa antes de reinventar",
  guide_devtips_3_text: "El sistema ya prioriza reusar moldes existentes cuando son compatibles. Mencionar una función parecida a algo que ya construiste ayuda a que la IA la reconozca.",
  guide_example_vague: "Quiero una app para mis gastos.",
  guide_label_vague: "Vago",
  guide_label_clear: "Claro",
  guide_example_clear: "Quiero anotar mis gastos del mes: fecha, monto, categoría (comida, transporte, etc.) y una nota opcional. Quiero verlos en una lista, poder editarlos o borrarlos, y ver el total gastado del mes.",

  guide_seo_title: "Cómo pedir tu app paso a paso | Ayuda de MEITI",
  guide_seo_description: "Aprende cómo funciona el asistente de IA de MEITI y cómo escribir el pedido ideal para que la primera versión de tu app salga bien.",
  guide_tab_you: "Para ti",
// 🏅 [POR QUÉ MEITI 2026-08-24] Pestaña de argumentos. Todo lo que se afirma acá está
  // construido y verificable en el producto — nada de promesas a futuro.
  guide_tab_why: "Por qué MEITI",

  why_hero_title: "La diferencia no es que escriba la app. Es que la prueba antes de dártela.",
  why_hero_text: "Cualquier generador con IA te devuelve código en minutos. El problema aparece después: ¿funciona de verdad? En MEITI, ninguna app llega a tus manos sin pasar tres controles automáticos, y si algo falla, el sistema lo repara solo antes de mostrártela.",

  why_sec_control_title: "Los tres controles que pasa cada app",
  why_sec_control_subtitle: "Automáticos, en cada app y en cada página nueva. Si alguno falla, la app no se aprueba.",
  why_control_1_title: "Pentágono: la estructura",
  why_control_1_text: "Un análisis determinístico (sin IA, siempre el mismo resultado) mide cinco ejes: estructura de datos, dependencias, flujos de información, eficiencia de render y lógica. Si el puntaje no alcanza, no pasa.",
  why_control_2_title: "Revisión del código",
  why_control_2_text: "Una segunda IA lee el código buscando errores reales: datos que no se guardan, campos que se pisan, pantallas que quedarían vacías, fugas de información entre usuarios. No revisa gustos de diseño: revisa lo que rompe.",
  why_control_3_title: "Prueba de uso real",
  why_control_3_text: "Un robot abre tu app como lo haría una persona: navega, completa formularios, hace clic en los botones y verifica que los datos aparezcan. Solo si logra usarla de verdad, la app queda aprobada.",

  why_sec_cura_title: "Aprende de cada error, para todas las apps",
  why_sec_cura_subtitle: "Es lo que ningún generador hace: el sistema mejora solo con el uso.",
  why_cura_1_title: "El error se corrige una vez",
  why_cura_1_text: "Cuando se detecta un problema, se repara solo la pieza afectada, nunca se rehace la app entera. Lo que ya estaba bien se queda como está.",
  why_cura_2_title: "Y no vuelve a nacer",
  why_cura_2_text: "Si el mismo tipo de error aparece en dos apps distintas, el sistema lo convierte en una regla permanente. A partir de ahí, ninguna app nueva vuelve a nacer con ese error.",
  why_cura_3_title: "Las piezas se acumulan",
  why_cura_3_text: "Cada app aporta sus componentes ya probados a una biblioteca compartida. Cuanto más se usa MEITI, más rápido y mejor nacen las apps siguientes.",

  why_sec_tuya_title: "La app es tuya, en serio",
  why_sec_tuya_subtitle: "Sin quedar atado a nosotros para siempre.",
  why_tuya_1_title: "Instalador de escritorio",
  why_tuya_1_text: "Windows, Mac y Linux. La app corre en la computadora con su propia base de datos local, sin depender de internet ni de nuestros servidores.",
  why_tuya_2_title: "Android y iOS",
  why_tuya_2_text: "Se genera el proyecto móvil completo, listo para compilar e instalar en el teléfono.",
  why_tuya_3_title: "El código fuente completo",
  why_tuya_3_text: "Te puedes llevar todo el proyecto, con sus flujos de compilación automática ya configurados para GitHub. Es tu código: sigue trabajándolo con quien quieras.",

  why_sec_backend_title: "Con todo lo de atrás ya resuelto",
  why_sec_backend_subtitle: "Lo que normalmente pide un backend aparte, acá viene incluido.",
  why_backend_1_title: "Base de datos propia por app",
  why_backend_1_text: "Cada app nace con su propio almacén de datos, aislado del resto. No compartes base con nadie y no hay que configurar nada.",
  why_backend_2_title: "Usuarios y sesión",
  why_backend_2_text: "Login por código al email, sin contraseñas que recordar ni que perder. Cada usuario ve solo sus propios datos.",
  why_backend_3_title: "Conexiones externas seguras",
  why_backend_3_text: "Si tu app usa un servicio de afuera (una IA, un servicio de clima, una API de pagos), la llave secreta se guarda del lado del servidor y nunca viaja al navegador de tus usuarios.",
  why_backend_4_title: "Cobros integrados",
  why_backend_4_text: "Puedes cobrar dentro de tu app y recibir el dinero en tu propia cuenta, sin montar una pasarela de pagos por tu cuenta.",

  why_sec_vs_title: "Comparado con las otras opciones",
  why_vs_trad_title: "Contratar desarrollo",
  why_vs_trad_text: "Meses de espera y presupuestos altos. Cada cambio depende de la agenda de otra persona. Aquí pides el cambio y lo tienes.",
  why_vs_otros_title: "Otros generadores con IA",
  why_vs_otros_text: "Te entregan el código y ahí termina su trabajo: si la app tiene un error, lo descubres tú usándola. MEITI la prueba antes, la repara sola y aprende de lo que encontró.",
  why_vs_nocode_title: "Plataformas sin código",
  why_vs_nocode_text: "Te dan piezas fijas para armar y te quedas dentro de su sistema para siempre. Aquí el código es tuyo y te lo puedes llevar.",

  why_cierre_title: "Empieza describiendo tu idea",
  why_cierre_text: "No hace falta que sepas de tecnología ni que tengas todo pensado. El asistente te hace unas preguntas cortas y se encarga del resto.",
  why_cierre_boton: "Crear mi app",
  guide_tab_devs: "Para developers",
  guide_example_title: "Un ejemplo, el mismo pedido de dos formas",
  guide_example_caption: "La de la derecha le da a la IA algo concreto para construir. La de la izquierda la obliga a adivinar todo.",

  // --- Servicios ---
  svc_page_title: "Servicios a medida",
  svc_tab_client: "Pedir un desarrollo",
  svc_tab_retainer: "Retainer mensual",
  svc_tab_dev: "Ofrezco servicios",
  svc_ex_appointments: "Sistema de turnos para un consultorio",
  svc_ex_store: "Tienda online con pagos",
  svc_ex_delivery: "App de reparto con seguimiento",
  svc_ex_panel: "Panel interno para mi equipo",
  svc_ex_integration: "Integrar mi sistema con otro",
  svc_loading_request: "Cargando tu pedido...",
  svc_input_placeholder: "Necesito un desarrollo...",
  svc_pick_dev: "Elige un desarrollador",
  svc_working_with: "Vas a trabajar con",
  svc_searching_devs: "Buscando devs disponibles...",
  svc_define_milestones: "Define los hitos del proyecto",
  svc_milestone_example: "Ej: Diseño y primera pantalla",
  svc_awaiting_confirmation: "Esperando confirmación",
  svc_milestones: "Hitos",
  svc_confirm_identity: "Confirma que eres tú",
  svc_code_sent_to: "Te mandamos un código a",
  svc_email_placeholder: "tu@email.com",
  svc_code_placeholder: "123456",
  svc_thanks_review: "¡Gracias por tu reseña!",
  svc_rate_dev: "Califica al desarrollador",
  svc_comment_optional: "Comentario (opcional)",
  svc_dev_email: "Email del desarrollador",
  svc_monthly_amount: "Monto mensual (USD)",
  svc_active_retainers: "Tus retainers activos",
  loading: "Cargando...",
  svc_profile_saved: "Perfil guardado.",
  svc_skills: "Habilidades (separadas por coma)",
  svc_skills_placeholder: "react, node, sqlite",
  svc_tools: "Herramientas (separadas por coma)",
  svc_tools_placeholder: "figma, git, docker",
  svc_username: "Nombre de usuario",
  svc_username_placeholder: "Cómo quieres que te vean en MEITI",
  svc_avatar: "Avatar de tu perfil",
  svc_portfolio: "Portfolio (una URL por línea)",
  svc_title: "Título",
  svc_title_placeholder: "ej: Desarrollador full-stack especializado en apps de gestión",
  svc_desc_placeholder: "Cuenta en una frase qué tipo de proyectos haces y para quién.",
  svc_packages: "Paquetes de servicio a precio fijo",
  svc_package_example: "Ej: Configuro tu chatbot de WhatsApp con IA",
  svc_package_includes: "Qué incluye...",
  svc_package_price: "Precio en USD, ej: 150",
  svc_package_days: "Días para entregar, ej: 3",
  svc_no_packages: "Todavía no tienes paquetes.",

  svc_seo_title: "Servicios a medida con desarrolladores reales | MEITI",
  svc_seo_description: "Cuéntanos tu proyecto y te conectamos con un desarrollador. Pago en custodia por hitos, liberado cuando apruebas cada entrega.",
  svc_page_description: "Un desarrollo hecho por un dev real, armado a partir de tu pedido, con el pago en custodia hasta que apruebes cada entrega.",
  svc_chat_intro: "Cuéntanos qué necesitas. Un par de preguntas y armamos el pedido para pasárselo a un dev.",
  showcase_fallback_title: "Lo que puedes hacer con MEITI",

  // --- Mis apps ---
  my_page_description: "Tus apps, pedidos y trabajos en un solo lugar.",
  my_tab_apps: "Apps",
  my_tab_requests: "Pedidos",
  my_tab_jobs: "Trabajos",
  my_no_apps: "Todavía no pediste ninguna app con esta cuenta.",
  my_no_custom_requests: "Todavía no pediste ningún desarrollo a medida.",
  my_no_assigned_jobs: "Todavía no tienes ningún pedido de servicios asignado.",
  my_planning_note: "Planificación, tiempos, ideas. Nunca código.",
  my_ask_about_job: "Pregúntale algo sobre este trabajo...",
  my_complexity: "Complejidad:",
  my_client_budget: "Presupuesto estimado del cliente:",
  my_delete_project: "Borrar proyecto",
  my_generating: "Generando tu app...",
  my_ai_connection_failed: "No se pudo completar por una falla de conexión con la IA.",
  my_platform: "Plataforma",
  my_published: "¡Publicada!",
  my_published_note: "Ya está visible en el marketplace para que otros la compren.",
  my_publish: "Publicar en marketplace",
  my_revenue_note: "Te queda el 70% de cada venta (comisión estándar).",
  my_app_desc_placeholder: "Qué hace la app, para quién es...",
  my_demo_link: "Link de video demo (opcional)",
  my_category: "Categoría",
  my_category_general: "General",
  my_price: "Precio (USD)",
  done: "Listo",
  my_write_here: "Escribe acá...",

  my_seo_title: "Mis apps | MEITI",
  my_login_title: "Ingresa a Mis apps",
  login_code_note: "Te mandamos un código de acceso. Sin contraseñas.",
  login_peek_prompt: "¿Prefieres mirar antes de entrar?",
  login_send_code: "Enviar código",
  login_verify: "Verificar",
  login_verifying: "Verificando...",

  login_check_email: "Revisa tu email",
  login_code_6_digits: "Te mandamos un código de 6 dígitos a",

  svc_picked_from_profile: "Elegiste este desarrollador directo desde su perfil, así que se salta el matching automático.",
  svc_complete_profile: "Completa tu perfil para que los clientes que arman un pedido te vean como opción.",
  svc_no_payout: "Todavía no configuraste cómo cobrar. Sin esto no puedes recibir hitos ni retainers.",
  my_review_done: "Revisión terminada. Ya puedes aplicar o descartar.",
  my_invite_devs: "Invita a otros devs y ganas un % de cada venta que hagan. Nunca les cuesta de más a ellos:",
  profile_pick_avatar: "Elige un avatar y cómo quieres que te identifiquen.",
  profile_nickname_note: "Nunca es tu nombre real. Es un apodo, solo para identificarte acá.",
  support_what_need: "¿Qué necesitas?",
  support_to_wizard: "Te llevamos al asistente de creación.",
  support_about_what: "¿Sobre qué quieres hablarnos?",
  support_which_app: "¿Sobre cuál de tus apps es?",

  // --- Categorias ---
  sort_price_asc: "Precio ↑",
  sort_price_desc: "Precio ↓",
  market_buy: "Comprar",
  market_subscribe: "Suscribirme",
  market_per_month: "/mes",
  market_zone_products: "Productos",
  product_sub_active: "Suscripción al día",
  product_sub_past_due: "Pago pendiente — hay un período de gracia antes de desactivarse",
  product_sub_cancelled: "Cancelada — sigue activa hasta el fin del período de gracia",
  product_sub_manage_billing: "Gestionar facturación",
  market_subscribe_login_needed: "Necesitas iniciar sesión para suscribirte — es una cuenta real, no una prueba.",
  market_subscribe_ask_title: "¿Cómo se llama tu negocio? (esto arma el link de tu instancia)",
  by: "por",
  market_audit: "Auditoría MEITI",
  market_no_video: "Sin video todavia.",
  market_no_description: "Sin descripcion todavia.",
  cat_finance: "Finanzas",
  cat_tasks: "Tareas",
  cat_commerce: "Comercio",
  cat_education: "Educación",
  cat_health: "Salud y fitness",
  cat_industrial: "Industrial",
  cat_communication: "Comunicación",
  cat_data: "Datos y analítica",
  cat_home: "Hogar",
  cat_events: "Eventos",
  cat_content: "Contenido",
  cat_general: "General",

  language: "Idioma",

  sign_out: "Salir",
  my_notify_ready: "Avisarme cuando esté lista",
  my_notify_ready_plural: "Avisarme cuando estén listas",
  app_state_ready: "Lista",
  app_state_building: "Creándose",
  app_state_error: "Con error",
  app_state_review: "En revisión",
  app_screens_one: "{n} pantalla",
  app_screens_many: "{n} pantallas",
  app_no_screens: "Sin pantallas",

  my_in_progress: "En desarrollo",
  my_see_dev_tools: "Ver Herramientas Dev",
  my_app_ready_to_build: "Tienes una app lista para crear",
  my_build_now: "Crear ahora",
  my_trial_waiting: "Tienes una prueba gratis esperando",
  my_try_now: "Probar ahora",
  discard: "Descartar",
  my_build_first: "Crear mi primera app",
  retry: "Reintentar",
  my_export: "Exportar",
  my_installer: "Instalador",
  my_publish_short: "Publicar",
  my_request_change: "Pedir cambio",
  my_open: "Abrir",
  my_cancel_refund: "Cancelar y devolver crédito",
  refresh: "Actualizar",
  my_test: "Probar",
  my_apply_changes: "Aplicar cambios",
  my_see_marketplace: "Ver marketplace",
  close: "Cerrar",
  copy: "Copiar",
  my_keep_talking: "Seguir hablando",
  accept: "Aceptar",
  reject: "Rechazar",
  my_remove_flag: "Quitar marca",
  my_remove_from_account: "Quitar de mi cuenta",
  my_generate: "Generar",
  my_recover: "Recuperar",
  less: "Menos",
  more: "Más",
  my_sync: "Sync",
  my_confirm_start: "Confirmar y empezar",
  my_still_reviewing: "Todavía se está revisando",

  my_opening_payment: "Abriendo pago...",
  my_recovering: "Recuperando...",
  my_creating: "Creando...",

  my_removing: "Quitando...",

  credits_account_total: "Total de tu cuenta ({email}).",

  // --- Historial de creditos (etiquetas que guarda el backend) ---
  mov_forge_app: 'Crear "{app}" (nivel {nivel})',
  mov_forge_failed: "La creación no llegó a completarse",
  mov_manual_adjust: "Ajuste manual del arquitecto",
  mov_dev_trial_bonus: "Bono de activación del trial gratis de Plan Developer ({dias} días)",
  mov_change_request: 'Pedido de cambio: "{resumen}"',
  mov_generate_page: 'Generar página "{pagina}"',
  mov_welcome_credits: "Créditos de bienvenida por registrarte",
  mov_tablero_pieza_ia: "Pieza generada por la Forja en el Tablero",
  mov_tablero_pagina: "Página guardada en el Tablero",
  mov_editor_claude: "Mensaje al Editor con IA",
  mov_agente_editor_dev: "Mensaje al agente del Editor con IA",

  showcase_title: "Inspírate con lo que ya se creó",
  showcase_a_creator: "un creador MEITI",

  credits_spent_month: "Gastado este mes",
  credits_spent_total: "Gastado en total",
  credits_bought_total: "Comprado en total",

  tools_brick_library: "Biblioteca",
  tools_bricks_premium: "Ladrillos (Premium)",
  tools_tablero: "Tablero",
  tablero_titulo: "El Tablero",
  tablero_subtitulo: "Acomoda las piezas de tu app sobre la grilla real. Una página a la vez.",
  tablero_candado_mensaje: "El Tablero es una herramienta de pago: entra con un plan activo, o si ya gastaste este mes lo mismo que el plan más económico.",
  tablero_sin_apps: "No tienes ninguna app disponible para abrir en el Tablero ahora mismo.",
  tablero_abrir_boton: "Abrir en el Tablero",
  tablero_seguir_editando: 'Seguir editando',
  tablero_abriendo: "Abriendo...",
  tablero_error_cargar_apps: "No se pudieron cargar tus apps.",
  tablero_error_abrir: "No se pudo abrir el Tablero.",
  tablero_error_cargar: "No se pudo cargar esta página.",
  tablero_error_guardar: "No se pudo guardar la página.",
  tablero_error_aplicar: "No se pudo aplicar el cambio.",
  tablero_error_descartar: "No se pudo descartar el cambio.",
  tablero_error_construir: "No se pudo construir el molde.",
  tablero_salir: "Salir",
  tablero_volver: "Volver",
  tablero_aplicar: "Aplicar cambios",
  tablero_aplicando: "Aplicando...",
  tablero_descartar: "Descartar",
  tablero_descartando: "Descartando...",
  tablero_confirmar_aplicar: "Esto reemplaza tu app en vivo con lo que armaste acá. ¿Continuar?",
  tablero_confirmar_descartar: "Se descarta todo lo que armaste en esta sesión del Tablero, sin tocar tu app en vivo. ¿Continuar?",
  tablero_pagina_cobrada: "Página guardada. Se descontó 1 crédito.",
  tablero_pagina_gratis: "Página guardada, sin costo.",
  tablero_sin_pagina: "Esta app no tiene páginas.",
  tablero_pagina_vacia: "Esta página está vacía. Agrega una pieza desde la izquierda.",
  tablero_buscar_piezas: "Buscar piezas...",
  tablero_es_compuesto: "Molde compuesto (armado en el Tablero)",
  tablero_pieza_nueva: "Pieza nueva",
  tablero_elige_pieza: "Elige una pieza del lienzo para ver sus propiedades.",
  tablero_prop_titulo: "Titulo",
  tablero_prop_ancho: "Ancho",
  tablero_prop_orden: 'Orden',
  tablero_mover_arriba: 'Subir',
  tablero_mover_abajo: 'Bajar',
  tablero_quitar_pieza: "Quitar de la pagina",
  tablero_guardar_pagina: "Guardar página",
  tablero_construir_titulo: "Construir un molde",
  tablero_agregar_a_pagina: 'Agregar a la página',
  tablero_editar_molde: 'Editar este molde',
  tablero_editar_con_claude: 'Editar este molde con Claude',
  tablero_editar_manual: 'Editar el código a mano',
  tablero_pieza_manual_boton: 'Tú mismo',
  tablero_pieza_ia_boton: 'Pídesela a la Forja',
  tablero_pieza_ia_titulo: 'Pídesela a la Forja',
  tablero_pieza_ia_placeholder: 'Describe la pieza que te falta: qué hace, qué datos muestra o guarda...',
  tablero_pieza_ia_costo_aviso: 'Se cobra solo si la pieza queda lista. Si la Forja no puede generarla, no se cobra nada.',
  tablero_pieza_ia_enviar: 'Pedir a la Forja',
  tablero_pieza_ia_pidiendo: 'Pidiendo...',
  tablero_pieza_ia_generando: 'La Forja está generando tu pieza. Puedes seguir acomodando la página mientras tanto.',
  tablero_pieza_ia_exito: 'Pieza lista: "{nombre}". Ya la puedes agregar desde la biblioteca.',
  tablero_pieza_ia_reuso: 'Ya existía una pieza para esto: "{nombre}", se agregó a la página.',
  tablero_pieza_ia_error: 'La Forja no pudo generar la pieza: {error}',
  tablero_error_pedir_pieza: 'No se pudo pedir la pieza.',
  tablero_editar_titulo: 'Editar molde',
  tablero_divergido_aviso: 'Este molde se editó por fuera del Tablero (con Claude o el editor manual) después de la última vez que se guardó acá. Si lo editas y guardas desde acá, se va a pisar ese código.',
  tablero_confirmar_editar_divergido: 'Este molde se editó por fuera del Tablero. Si lo editas y guardas desde acá, se pisa ese código con lo que armes en este constructor.\n\n¿Editar de todos modos?',
  tablero_guardar_cambios_molde: 'Guardar cambios',
  tablero_construir_boton: "Construir y agregar",
  tablero_construyendo: "Construyendo...",
  tablero_nombre_molde: "Nombre del molde",
  tablero_tabla_datos: "Tabla de datos",
  tablero_tabla_hija: "Tabla hija",
  tablero_columna_fk: "Columna que apunta al padre",
  tablero_campos_maestro: "Campos",
  tablero_campos_detalle: "Campos del detalle",
  tablero_agregar_campo: "Agregar campo",
  tablero_agregar_detalle: "Agregar un detalle (maestro-detalle)",
  tablero_campo_columna: "columna",
  tablero_campo_etiqueta: "etiqueta",
  tablero_campo_texto: "texto",
  tablero_renombrar_pagina: "Renombrar página",
  tablero_mover_pagina_izquierda: "Mover a la izquierda",
  tablero_mover_pagina_derecha: "Mover a la derecha",
  tablero_error_renombrar_pagina: "No se pudo renombrar la página.",
  tablero_error_reordenar_paginas: "No se pudo cambiar el orden de las páginas.",
  tablero_renombrar_molde: "Renombrar este molde",
  tablero_error_renombrar_molde: "No se pudo renombrar el molde.",
  tools_claude_editor: "Editor con IA",
  tools_pentagon_audit: "Auditoría Pentágono",
  tools_seo_title: "Herramientas para Devs | MEITI",
  tools_seo_description: "Panel de herramientas avanzadas para desarrolladores suscritos al Plan Developer.",
  tools_page_title: "Herramientas para desarrolladores",
  tools_subscribe_dev: "Suscribirme al Plan Developer",
  lego_seo_title: "Lego Panel | MEITI",
  lego_seo_description: "Arma un panel chico gratis ensamblando piezas ya probadas, sin generar código nuevo.",
  lego_unavailable: "Lego Panel todavía no está disponible por acá.",
  showcase_top_devs: "Devs mejor valorados",
  trial_need_skill_bio: "Completa al menos una habilidad y una bio corta.",
  trial_activation_failed: "No se pudo activar el trial.",
  trial_skills_placeholder: "Habilidades (ej. React, Node, SQL)",
  trial_bio_placeholder: "Bio corta (una línea sobre ti)",
  trial_activating: "Activando...",
  trial_activate: "Activar trial gratis",
  made_with_meiti: "Hecho con MEITI",
  tap_one_to_start: "Toca una para empezar la tuya con esa idea.",

  nosession_needs_account: "{nombre} necesita una cuenta. Es gratis y toma un minuto.",
  nosession_signin_credits: "Entrar y ganar {n} créditos gratis",

  tools_page_description: "Biblioteca, Auditoría y Marketplace son gratis para cualquier dev registrado. Editor con IA y Lego Panel son parte del Plan Developer.",

  // --- Industrial (AutoMach) ---
  ind_seo_title: "Automatiza tu máquina industrial con IA | MEITI",
  ind_seo_description: "Conecta tu PLC o máquina real por Modbus u OPC-UA y genera una app de control a medida, corriendo en tu propia red.",
  ind_page_description: "Conecta tu PLC o máquina real y generamos una app de control a medida.",
  ind_chat_intro: "Cuéntame qué máquina quieres automatizar. Un par de preguntas y armamos el proyecto.",
  ind_input_placeholder: "Automatízame una máquina...",
  ind_ex_irrigation: "Controlar el riego de un invernadero",
  ind_ex_packer: "Panel de control de una envasadora",
  ind_ex_coldroom: "Monitorear la temperatura de una cámara fría",
  ind_ex_lighting: "Automatizar la iluminación de una planta",
  ind_review_note: "¿Está todo bien? Puedes corregir cualquier respuesta o agregar algo antes de generar la app.",
  ind_edit_answer: "Editar esta respuesta",
  ind_back_to_project: "Volver al proyecto",
  ind_save_continue: "Guardar cambios y continuar",
  ind_all_good: "Todo bien, continuar",
  ind_preparing: "Preparando tu proyecto...",
  ind_your_project: "Tu proyecto",
  ind_hardware: "Hardware",
  ind_pending_confirm: "Pendiente de confirmar",
  ind_no_points: "Sin puntos todavía.",
  ind_status: "Estado",
  ind_review_interview: "Revisar entrevista",
  ind_go_my_apps: "Ir a Mis apps",
  ind_building: "Armando tu app de control...",
  ind_takes_a_minute: "Esto puede tardar un minuto. No cierres esta pantalla.",
  ind_app_coming: "¡Tu app está en camino!",
  ind_automate_another: "Automatizar otra máquina",
  ind_start_over: "Empezar de nuevo",
  ind_login_title: "Inicia sesión para continuar",
  ind_error_edit: "No se pudo editar la entrevista.",
  ind_error_project: "No se pudo crear el proyecto.",
  ind_error_scanner: "No se pudo descargar el escáner.",
  ind_error_upload: "No se pudo subir el archivo.",
  ind_error_bad_profile: "El archivo no es un perfil.json válido.",
  ind_error_generate: "No se pudo generar la app.",
  save: "Guardar",
  add: "Agregar",

  // --- Perfil de creador ---
  prof_summary: "Resumen",
  prof_apps_for_sale: "Apps en venta",
  prof_reviews: "Reseñas",
  prof_seo_title: "Perfil de creador | MEITI",
  prof_error_load: "No se pudo cargar este perfil.",
  prof_not_found: "Este creador no existe.",
  prof_page_title: "Perfil de creador",
  prof_page_description: "La ficha pública de un dev: sus servicios, su reputación y cómo contactarlo.",
  prof_verified: "Identidad verificada",
  prof_hire: "Contratar servicio",
  prof_see_market_apps: "Ver apps en el market",
  prof_skills: "Habilidades",
  prof_no_profile: "Todavía no completó su perfil.",
  prof_no_portfolio: "Todavía no agregó nada a su portfolio.",
  prof_no_reviews: "Todavía no tiene reseñas.",
  prof_custom_service: "Servicio a medida",
  prof_no_apps: "Todavía no tiene apps publicadas.",
  prof_need_custom: "¿Necesitas algo a medida?",
  prof_tell_project: "Cuéntanos tu proyecto. La IA arma el pedido y se lo manda directo a este desarrollador.",
  prof_packages: "Paquetes disponibles",
  prof_no_packages: "Todavía no tiene paquetes a precio fijo.",

  prof_no_packages_own: 'Todavía no armaste ningún paquete. Hazlo desde "Ofrezco servicios".',

  // --- Cierre de la migracion ---
  wiz_own_login: "Tu app va a tener login propio",
  wiz_error_create: "No se pudo crear la app.",
  wiz_error_create_conn: "Fallo al crear la app.",
  wiz_sender_placeholder: 'Remitente, ej: "Mi Empresa <codigos@miempresa.com>"',
  ind_building_app: "Estamos armando tu app...",
  tools_complete_profile: 'Completa tu perfil en Servicios, en "Ofrezco servicios"',
  login_default_title: "Inicia sesión",
  prof_unavailable: "No disponible",
  prof_tab_services: "Servicios",
  prof_tab_portfolio: "Portafolio",
  prof_available: "Disponible",
  prof_error_save: "No se pudo guardar tu perfil.",
  prof_your_profile: "Tu perfil en MEITI",
  chat_back_to_last: "Volver al último mensaje",
  showcase_automate: "Automatiza tu máquina",
  showcase_create_app: "Crea tu app",
  showcase_build_panel: "Arma tu panel",
  showcase_more_panels: "Ver más paneles",
  showcase_more_apps: "Ver más apps",
  sup_app_bug: "Bug de una app",
  sup_app_bug_desc: "Algo no funciona como esperabas en una app que te generamos.",
  sup_payment: "Pago o devolución",
  sup_payment_desc: "Un problema con un cobro, o quieres pedir una devolución.",
  sup_idea_desc: "Una idea para mejorar MEITI.",
  sup_account: "Cuenta o acceso",
  sup_account_desc: "No puedes entrar, o algo pasa con tu cuenta.",
  sup_other_desc: "Algo que no entra en las anteriores.",
  error_generic_dot: "Algo salió mal.",
  sup_new_app: "Crear una app nueva",
  sup_report_desc: "Reportar un problema, un pago, o dejar una sugerencia.",
  sup_tell_what_happened: "Cuéntame qué pasó, con el detalle que puedas.",
  svc_error_load_request: "No se pudo cargar tu pedido.",
  svc_pick_from_list: "Elige un desarrollador de la lista.",
  svc_need_milestone: "Define al menos un hito con título y monto.",
  svc_error_assign: "No se pudo asignar el desarrollador.",
  svc_error_release: "No se pudo liberar el pago.",
  svc_assign_milestones: "Asignar y crear hitos",
  svc_approve_release: "Aprobar y liberar pago",
  svc_error_send_code: "No se pudo enviar el código.",
  svc_wrong_code: "Código incorrecto.",
  svc_error_retainer: "No se pudo iniciar el retainer.",
  svc_you_pay: "Tú pagas",
  svc_you_get_paid: "Te pagan",
  svc_error_payouts: "No se pudo iniciar la configuración de cobros.",
  svc_your_avatar: "Tu avatar",
  svc_error_package: "No se pudo crear el paquete.",
  my_unpaid: "Sin pagar",
  my_untitled_request: "Pedido sin título",
  my_error_assistant: "No se pudo consultar el asistente.",
  my_error_reply: "No se pudo responder el pedido.",
  my_error_build: "No se pudo iniciar la compilación.",
  my_error_installer: "No se pudo descargar el instalador.",
  my_retrying: "Reintentando tu pedido. La app vuelve a revisión.",
  my_error_cancel: "No se pudo cancelar el pedido.",
  my_error_preview: "No se pudo generar el preview.",
  my_error_sync: "No se pudo sincronizar los datos.",
  my_already_synced: "Ya estaba todo al día, no había datos nuevos.",
  my_error_apply: "No se pudo aplicar el cambio.",
  my_error_discard: "No se pudo descartar.",
  my_error_discard_change: "No se pudo descartar el cambio.",
  my_hardware_unconfirmed: "Hardware sin confirmar",
  my_generating_short: "Generándose...",
  my_error_publish: "No se pudo publicar.",
  my_error_message: "No se pudo procesar el mensaje.",
  my_error_start_change: "No se pudo iniciar el cambio.",
  my_tell_change: "Cuéntame qué quieres agregar, cambiar o quitar.",

  my_error_retry: "No se pudo reintentar.",
  my_confirm_delete: "¿Borrar este proyecto? No se puede deshacer.",
  my_error_recover: "No se pudo recuperar la app.",
  my_error_export: "No se pudo exportar la app.",
  my_error_remove: "No se pudo quitar la app de tu cuenta.",
  my_error_page: "No se pudo generar la página.",
  my_generating_page: "Generando tu página. La app vuelve a revisión.",
  my_error_discard_page: "No se pudo descartar la página.",
  my_error_update: "No se pudo aplicar la actualización.",
  my_error_retry_request: "No se pudo reintentar el pedido.",
  my_sell_a_lot: "¿Vendes mucho? Paga menos →",
  my_setup_payouts: "Configurar cómo cobrar →",
  svc_packages_note: "Atajo tipo Fiverr para trabajos repetibles. No necesita el chat con IA: el cliente compra directo desde tu perfil.",

  // --- Dev tools (Lego Panel, Herramientas) ---
  dt_confirm: "Confirmar",
  dt_back: "Volver",
  dt_search: "Buscar...",
  dt_no_results: "Sin resultados.",
  dt_mold_name: "Nombre del molde",
  dt_save_as_own: "Guárdalo como molde propio de una de tus apps:",
  dt_loading_apps: "Cargando tus apps...",
  dt_no_own_apps: "Todavía no tienes apps propias. Crea una primero desde el wizard.",
  dt_pick_app: "Elige una app...",
  dt_cloning: "Clonando...",
  dt_error_clone: "No se pudo clonar el molde.",
  dt_search_by_name: "Buscar por nombre o id...",
  dt_error_undo: "No se pudo deshacer.",
  dt_undo_tooltip: "Volver a la versión de antes del último guardado",
  dt_undoing: "Deshaciendo...",
  dt_undo: "Deshacer",
  aud_matter: "Materia",
  aud_energy: "Energía",
  aud_information: "Información",
  aud_time: "Tiempo",
  aud_intelligence: "Inteligencia",
  aud_monolith: "Posible monolito: un molde concentra demasiada lógica o estado.",
  aud_collapsed_field: "Hay un campo colapsado por falta de flex-1 en su contenedor.",
  aud_unmaterialized: "Hay moldes todavía sin materializar (código volátil).",
  aud_no_settings: "App multi-página sin una sección de perfil o configuración.",
  aud_error: "No se pudo auditar esta app.",
  aud_no_apps: "Todavía no tienes apps aprobadas (ONLINE) para auditar.",
  aud_auditing: "Auditando...",
  aud_would_pass: "Aprobaría",
  aud_would_fail: "No aprobaría",
  aud_points_to_check: "Puntos a revisar",
  ed_error_load: "No se pudo cargar el código.",
  ed_error_assistant: "No se pudo contactar al asistente.",
  ed_unavailable: "El Editor con IA no está disponible por ahora.",
  ed_no_own_molds: "Todavía no tienes apps con moldes propios.",
  ed_edit_with_code: "Editar con Code/Ver",
  ed_yes_load: "Sí, cargar",
  ed_loading_editor: "Cargando editor...",
  ed_error_save: "No se pudo guardar.",
  ed_restored: "Se restauró la versión anterior de este molde.",
  ed_saving: "Guardando...",
  ed_no_changes: "Sin cambios todavía.",
  ed_no_online_apps: "Todavía no tienes apps en línea (ONLINE) para editar.",
  ed_no_vitrinas: "Todavía no tienes ninguna vidriera del Marketplace.",
  ed_filtro_mis_apps: "Mis apps",
  ed_filtro_vitrinas: "Vitrinas",
  ed_clon_activo_volver: "Tienes un cambio en curso en esta app — toca para volver a su pestaña.",
  ed_clon_aviso: "Trabajando sobre una copia — nada de esto es visible para tus usuarios todavía.",
  ed_clon_sync: "Sincronizar",
  ed_clon_apply: "Aplicar cambios",
  ed_clon_discard: "Descartar",
  ed_clon_espera_revision: "Espera a que se habilite la revisión antes de aplicar.",
  ed_sync_error: "No se pudo sincronizar.",
  ed_apply_error: "No se pudo aplicar el cambio.",
  ed_discard_error: "No se pudo descartar.",
  ed_pick_app_to_see: "Elige una app arriba para ver su visor en vivo.",
  ed_visor_error: "No se pudo cargar el visor de esta app.",
  ed_cambios_aplicados: "Cambios aplicados. Elige una app arriba para seguir — la misma u otra.",
  ed_aplicando_en_curso: "Aplicando los cambios a la app real...",
  ed_descartando_en_curso: "Descartando la copia de trabajo...",
  ed_cambios_descartados: "Cambios descartados. Elige una app arriba para seguir — la misma u otra.",
  ed_tab_chat: "Chat",
  ed_tab_visor: "Visor",
  ed_placeholder_no_app: ["Elige una app arriba para empezar."],
  ed_credit: "crédito",
  ed_credits: "créditos",
  ed_tool_list: "Revisó las piezas de tu app",
  ed_tool_read: "Leyó",
  ed_tool_kit: "Consultó soluciones ya probadas",
  ed_tool_apply: "Aplicó un cambio en",
  ed_tool_image: "Generó una imagen de diseño",
  ed_tool_video: "Generó un video de diseño",
  ed_tool_failed: "falló",
  ed_fullscreen: "Pantalla completa",
  ed_exit_fullscreen: "Volver a la pantalla normal",
  ed_see_more_apps: "Ver más apps",
  ed_back_to_apps: "Volver",
  ed_model_label: "Modelo",
  ia_free_aviso_privacidad: "Meiti AI Free usa proveedores con nivel gratis (Groq, NVIDIA y Gemini). Lo que se genera puede reusarse para reentrenar los modelos de MEITI, y esos proveedores pueden usar lo que reciben para mejorar los suyos. Si tu app tiene código o datos privados, elige otro modelo.",
  ed_spend_see_more: "Ver el detalle en Créditos",
  ed_undo: "Deshacer",
  ed_undone: "Deshecho",
  ac_title: "Asistente de Contenido MEITI",
  ac_placeholder: "Puedo generar imágenes, videos, crear y guardar registros de lo que necesites en la app.",
  ac_close: "Cerrar",
  ac_discard: "Descartar",
  ac_apply: "Aplicar",
  ac_applying: "Aplicando…",
  ac_applied: "Listo. Los cambios ya están en tu app.",
  ac_discarded: "Descartado. Tu app sigue como estaba.",
  ac_preview_loading: "Cargando la vista previa…",
  ac_preview_empty: "Escribe tu primer pedido para empezar.",
  ac_switch_description: "Crea datos de ejemplo para que tu app deje de verse vacía, pero no se queda ahí: también genera imágenes y videos, y crea registros reales de lo que necesites (clientes, productos, lo que sea), de a varios a la vez. Hablas en tus palabras, sin tocar código.",
  voz_start: "Dictar por voz",
  voz_stop: "Detener el dictado",
  voz_error_permiso: "No se pudo activar el micrófono. Revisa el permiso en tu navegador.",
  voz_error_contexto: "El dictado por voz necesita una conexión segura (https). Probando por IP local no funciona, sí va a andar en meiti.dev.",
  voz_error: "No se pudo usar el dictado por voz. Prueba de nuevo.",
  adj_tooltip: "Adjuntar imagen o PDF",
  adj_quitar: "Quitar adjunto",
  adj_tipo_invalido: "Ese tipo de archivo no está permitido. Solo imágenes (JPG/PNG/WEBP) o PDF.",
  adj_demasiado_grande: "El archivo es demasiado grande (máximo 12MB).",
  adj_error_lectura: "No se pudo leer el archivo. Prueba de nuevo.",
  adj_sin_modelo_gratis: "Meiti AI Free no soporta archivos adjuntos. Cambia a Haiku o Gemini Flash para adjuntar algo.",
  brk_dev_only: "Exclusivo Plan Developer",
  brk_none_yet: "Todavía no hay ladrillos premium cargados.",
  lego_ex_trading: "Un panel de trading con precios en vivo",
  lego_ex_stock: "Un tablero de stock del depósito",
  lego_ex_sensors: "Un panel de sensores de una planta",
  lego_ex_sales: "Un resumen de ventas del mes",
  lego_see_guide: "Mira la guía",
  lego_error_assistant: "Falló el asistente.",
  lego_error_assemble: "No se pudo ensamblar el panel.",
  lego_ready: 'Tu panel ya está listo. Lo vas a ver en "Mis apps".',
  lego_build_another: "Armar otro panel",
  lego_recent_panels: "Los últimos paneles armados",
  lego_chat_intro: "Cuéntame qué panel quieres armar. Busco entre las piezas ya probadas y te sugiero cómo armarlo.",
  lego_input_placeholder: "Ármame un panel...",
  lego_yes_build: "Sí, ármalo así",
  lego_build_free: "Armar lo que hay (gratis)",
  lego_full_app: "Crear la app completa con IA",
  lego_adjust: "Ajustar selección",
  lego_search_pieces: "Buscar más piezas por nombre...",
  mold_tag_base: "base",
  mold_tag_premium: "premium",
  mold_tag_forged: "forjado",
  lego_panel_name: "Nombre del panel",
  lego_page_count: "Cantidad de páginas",
  lego_style: "Estilo",
  lego_create_panel: "Crear panel",
  mkd_error_stats: "No se pudieron leer tus estadísticas.",
  mkd_your_apps: "Tus apps en el marketplace",
  mkd_active: "Publicaciones activas",
  mkd_sales: "Ventas",
  mkd_commission: "Comisión MEITI descontada",
  mkd_your_requests: "Tus pedidos de servicios",
  mkd_assigned: "Asignados (activos)",
  mkd_completed: "Completados",
  mkd_your_milestones: "Tus hitos",
  mkd_paid_out: "Cobrados (liberados a ti)",
  mkd_in_escrow: "En custodia (pagados, sin liberar)",
  mkd_monthly_income: "Ingreso mensual comprometido",
  prv_render_failed: "Este molde falló al renderizar.",
  prv_clear: "Limpiar",

  aud_edited_by_hand: "Editaste un molde de esta app a mano desde Herramientas Dev después de la última verificación.",
  ed_reference_only: "Solo referencia. Carga el código en el chat y pídele a Claude que lo adapte.",
  ed_chat_placeholder: "Analiza esto, créame un molde de..., agrégale un filtro a...",
  brk_locked_note: "Estos ladrillos existen (ver la lista abajo), pero el código y el clonado quedan para el Plan Developer.",
  lego_assign_pieces: "Piezas elegidas. Asígnalas a una página:",
  lego_page_n: "Página 1",
  prv_paste_code: "Escribe o pega código en la pestaña Code para ver el preview acá.",
  prv_no_logs: "Sin logs todavía. Los console.log, warn y error del molde van a aparecer acá.",

  dt_library_note: "Ladrillos reusables ya probados en producción. Mismo criterio que usa la IA al crear: moldes base del sistema, o moldes de apps ya confirmadas por QA humano.",

  // --- Frases armadas (con variables) ---
  my_missing_pages: "Le faltan {n} página(s) del plan original. Todavía no está lista para uso real.",
  my_confirm_remove: '¿Quitar "{app}" de tu cuenta? No se borra, solo deja de aparecer acá. La puedes recuperar después.',
  my_confirm_discard_page: '¿Descartar la página "{pagina}"? No se cobra nada, pero no se puede deshacer.',
  my_page_label: "Página: {pagina}",
  prof_seo_description_dyn: "Perfil de {identidad} en MEITI: servicios, apps publicadas y reseñas de clientes reales.",
  aud_missing_credential: 'Declara conexión externa a "{apis}" pero no hay credencial cargada para esta app en Conexión de APIs.',
  aud_help_improve: "Ayúdame a mejorar el código de esta app para subir estos puntos. Te cargo o pego abajo el molde que quiero que revises.",
  dt_cloned_as: 'Clonado como "{nombre}". Ya lo tienes en "Editor con IA", en "Tus apps".',
  ed_code_loaded: 'Código cargado en "{molde}". La app vuelve a pedir confirmación de QA antes de ofrecerse como reusable.',
  ed_restored_named: 'Se restauró la versión anterior de "{molde}".',
  ed_undo_named: 'Deshacer último guardado en "{molde}"',
  lego_full_match: 'Con estas piezas te puedo armar "{panel}" completo: {piezas}. ¿Lo armamos así?',
  lego_partial_match: "Con lo que ya tengo te puedo armar, gratis: {piezas}. Para la idea completa falta {falta}. Eso ya necesita generar código nuevo y no es gratis. ¿Armamos lo que hay, o pasamos tu pedido al creador completo con IA?",
  lego_no_match: "No tengo piezas ya hechas para esto (falta {falta}). Armar esto necesita generar código nuevo. ¿Pasamos tu pedido al creador completo con IA?",
  lego_your_panel: "tu panel",
  lego_something_missing: "algo que no tengo como pieza ya hecha",
  lego_all_of_it: "todo lo que pediste",
  lego_page_num: "Página {n}",

  // --- Textos sueltos de interfaz ---
  credits_purchase_ok: "¡Listo! Tu compra se acreditó correctamente.",
  credits_sub_ok: "¡Listo! Tu suscripción quedó activa.",
  credits_payment_cancelled_balance: "Cancelaste el pago. Tu saldo no cambió.",
  credits_plans_coming: "Los planes mensuales todavía se están configurando. Mientras tanto puedes seguir usando créditos sueltos.",
  tools_free_note: "Biblioteca, Auditoría Pentágono y Marketplace son gratis para cualquier dev registrado:",
  tools_dev_plan_note: "El Editor con IA y Lego Panel son parte de la suscripción Plan Developer.",
  wiz_login_gift: "Entra con tu email y te damos {n} créditos gratis. No hace falta llenar ningún formulario: te mandamos un código y listo. Tu app queda como está, sigues desde acá.",
  wiz_signin_gift: "Entrar y recibir {n} créditos gratis",
  wiz_keep_as_is: "Seguir así",
  wiz_setup_later: "Configurar esto más tarde",
  purchase_cancelled: "Cancelaste la compra. No se te cobró nada.",
  market_no_listings: "No hay publicaciones en esta categoría.",
  trial_7_days: "7 días gratis de Plan Developer",
  trial_pitch: "Créditos para seguir construyendo y acceso a Herramientas, sin tarjeta. Solo completa tu perfil de dev.",
  svc_dev_unavailable: "Ese desarrollador no está disponible en este momento. Elige otro para seguir con tu pedido.",
  svc_no_devs: "Todavía no hay desarrolladores con perfil cargado. Prueba de nuevo más tarde.",
  svc_dev_notified: "Le avisamos al desarrollador de tu pedido. Está esperando que confirme si lo acepta.",
  svc_dev_timeout: "Si no responde a tiempo, el pedido vuelve solo a estar disponible y te mostramos otro match.",
  svc_retainer_note: "Un pago mensual recurrente a un dev con el que ya vienes trabajando. Sin custodia: cobra directo cada mes.",
  svc_retainer_active: "¡Retainer activo!",
  svc_none_yet: "Todavía no tienes ninguno.",
  svc_see_my_profile: "Ver mi perfil público →",
  svc_payouts_ready: "Ya puedes cobrar. Cuenta configurada.",
  svc_start_retainer: "Iniciar retainer",
  aud_intro: "Elige una de tus apps y corre el mismo motor de puntaje que ya usa la revisión autónoma de MEITI. Sin costo, no llama a ninguna IA.",
  brk_intro: "Ladrillos premium, construidos a mano por el equipo de MEITI y exclusivos del Plan Developer. No están disponibles en ningún otro lado.",

  my_pages_bundled: "Como tu pedido incluye pantallas nuevas ({n}), las generamos junto con la última que crees, así queda todo funcionando de una, en vez de dejarte botones que llevan a una pantalla que todavía no existe.",
  my_building_copy: "Estamos armando una copia de tu app para probar el cambio. La que ya está online sigue funcionando normal mientras tanto.",
  ind_app_coming_note: 'La estamos armando y un miembro del equipo la va a revisar antes de activarla. La vas a encontrar en "Mis apps" apenas esté lista. El siguiente paso, empaquetarla para tu Raspberry Pi, todavía es manual: te vamos a contactar.',
  ind_scanner_note: "Descarga el escáner, córrelo en una máquina conectada a tu equipo (o directo en la Raspberry Pi) y va a subir el resultado solo. Si esa red no tiene salida a internet, copia el archivo perfil.json que te va a dejar y súbelo acá abajo a mano.",
  ind_wiring_plan: "Este es el plano de conexión: qué pin controla o lee cada cosa, y qué hardware adicional hace falta.",
  tools_free_access_note: "Estás viendo las herramientas gratis por tener perfil de dev. El Editor con IA y Lego Panel son parte de la suscripción Plan Developer.",
  tools_architect_access: "Acceso habilitado por excepción del arquitecto. No hay una suscripción Plan Developer activa en esta cuenta.",

  my_discard_anyway: "{error}\n\n{lista}\n\n¿Descartarla igual?",
  my_extra_per_page: " + {n} créditos por cada una de las otras páginas nuevas, cuando las generes (la primera ya va incluida)",
  svc_days: "{n} días",
  aud_points_found: "Puntos que detectó:",
  lego_can_reuse: "(ya puedes reusar: {piezas})",
  my_waiting_no_credits: "Quedó esperando porque no te alcanzaban los créditos.",

  aud_result: 'La Auditoría Pentágono de "{app}" dio un promedio de {promedio} (línea base {base})',
  aud_would_not_pass_suffix: ", no llegaría a aprobar",
  ed_this_is_code: 'Este es el código de "{molde}":',
  lego_suggestion: "Sugerencia según tu pedido. Ajusta si hace falta ({n} / {max}):",

  sup_title: "Soporte MEITI",
  sup_need_support: "Necesito soporte",
  sup_new_report: "Nuevo reporte",
  sup_other_app: "Otra app o prefiero contarlo yo",
  sup_create_my_app: "Crear mi app",
  sup_architect: "Arquitecto MEITI",
  profile_rather_dev: "Prefiero registrarme como dev →",
  aud_pick_app: "-- Elige una app --",
  aud_baseline: "Línea base:",
  aud_previous_stable: "versiones estables previas",
  aud_average: "Promedio",
  aud_check_with_claude: "Chequear con Editor con IA",
  dt_clone: "Clonar",
  dt_view: "Ver",
  ed_load_into_mold: "Cargar código al molde:",
  prv_console: "Consola",
  prv_sample_note: "Preview con datos de muestra. Nunca es real: sirve para ver la forma del molde (tabla, formulario, etc.).",
  tools_see_more: "Ver más herramientas",
  ind_hardware_pending: 'Hay hardware sin confirmar todavía y nuestro equipo lo está revisando. "Generar la app" se habilita solo cuando esté listo.',
  ind_generate_app: "Generar la app",
  ind_download_scanner: "Descargar escáner",
  ind_project_ref: "Referencia del proyecto:",
  retry_keep_progress: "Reintentar (sin perder lo hecho)",
  ind_login_note: "El escáner descargable trae una credencial atada a tu cuenta. Te mandamos un código, sin contraseñas.",
  wiz_continue: "Continuar",
  wiz_can_close: "Ya puedes cerrar esta ventana, no hace falta que esperes acá. La estamos armando y un miembro del equipo la va a revisar antes de activarla.",
  wiz_reference: "Referencia:",
  wiz_asking_permission: "Pidiendo permiso...",
  wiz_we_will_notify: "Te vamos a avisar",
  wiz_we_will_email: "Te vamos a escribir a",
  wiz_create_another: "Crear otra app",
  market_nothing_yet: 'Todavía no hay nada publicado. Sé el primero desde "Mis apps".',
  market_new_badge: "Nueva",
  market_sold: "vendida",
  market_see_demo: "Ver video demo",
  my_ai_assistant: "Asistente IA",
  my_download: "Descargar",
  my_dev_plan_active: "Plan Developer activo: pagas comisión escalonada según cuánto vendas este mes, no el 30% fijo.",
  trial_to_activate: "para activar tu trial gratis de Plan Developer.",
  login_other_email: "Usar otro email",
  prof_trust_score: "Trust Score:",
  prof_completed_contracts: "contratos completados",
  prof_tell_project_link: "Cuéntame tu proyecto →",
  prof_delivery_days: "días de entrega",
  svc_payment_held: '¡Pago retenido con éxito! Cuando el dev entregue ese hito, aprieta "Aprobar" para liberarlo.',
  svc_estimated_budget: "Presupuesto estimado:",
  svc_pick_other_dev: "Elegir otro developer",
  svc_see_full_profile: "Ver perfil completo →",
  svc_add_milestone: "+ Agregar otro hito",
  svc_start_new_request: "Empezar un pedido nuevo",
  svc_paid: "Pagado",
  svc_bio: "Bio",
  svc_share_preview: "Cómo aparece tu perfil al compartirlo",
  svc_share_preview_hint: "(opcional, como el título y la descripción de un video en YouTube)",
  svc_available_projects: "Disponible para nuevos proyectos",
  svc_accepts_retainers: "Acepto retainers mensuales de empresas",
  showcase_more_devs: "Ver más devs",
  showcase_deliveries: "entregas",
  chat_tags: "Etiquetas",
  chat_close_help: "Cerrar ayuda",

  prof_services_link: "Servicios → Ofrezco servicios",
  prof_your_public_view: "Estás viendo tu perfil público tal como lo ve un visitante. Para editarlo, ve a",
  trial_sign_in_at: "Inicia sesión en",
  wiz_signin_to_see: 'Inicia sesión con tu email en "Mis apps" para verla apenas esté lista.',
  svc_complexity_sep: "· Complejidad:",

  svc_complexity: "Complejidad",

  lego_page_word: "Página",
  mkd_milestones_word: "hitos",
  mkd_retainers_word: "retainers",

  wiz_advanced_note: 'Elegiste el nivel Avanzado. Para dejar bien clara una app "pro" te vamos a hacer varias preguntas adicionales.',
  wiz_level_too_small: 'Tu pedido necesita más páginas de las que cubre el nivel "{actual}". Pasa a nivel "{sugerido}" para crear la app completa, o recorta el pedido acá abajo.',
  wiz_level_cheaper_note: 'Tu pedido entra en el nivel "{sugerido}", que cuesta menos créditos que el "{elegido}" que elegiste. Puedes bajar y pagar menos, o seguir así si quieres margen para agrandarla después.',
  wiz_use_level_cheaper: "Usar nivel {nivel} y pagar menos",
  wiz_resend_why: "Como cada persona va a entrar con su propia cuenta, necesitamos mandar códigos de acceso por email desde TU propia cuenta de Resend, no la de MEITI.",
  wiz_resend_step1: "Ve a",
  wiz_resend_step2: ", crea una cuenta gratis y genera una API key. Después pégala acá abajo. Nunca se la mostramos a nadie ni la escribimos en el código de tu app.",

  my_assistant_for: "Asistente · {titulo}",
  my_n_screens: "{n} pantalla(s)",
  my_build_failed: "falló: {motivo}",
  my_unknown_error: "error desconocido",
  my_copied_from: 'Copiado originalmente de "{molde}". Ese molde ya cambió.',
  my_wait_before_apply: "Todavía se está revisando. Espera antes de aplicar.",
  my_removed_apps: "Apps que quitaste ({n})",
  my_request_change_for: 'Pedir un cambio · "{app}"',
  my_new_pages: "Páginas nuevas ({n})",
  my_new_functions: "Funciones nuevas ({n})",
  my_function_where: "en {donde}",
  my_change_cost: "Este cambio cuesta {n} créditos.",
  my_will_create_copy: "Vamos a crear una copia de tu app para probar este cambio. La que ya está online sigue funcionando normal para tus usuarios mientras se prueba.",
  my_others_can_buy: 'Otros usuarios van a poder comprar una copia de "{app}".',
  my_change_in_progress: 'Cambio en curso: "{app}"',
  my_mold_updates: "Actualizaciones de moldes disponibles ({n})",
  my_pending_pages: "Páginas pendientes ({n})",
  my_installer_for: "Instalador de {plataforma}:",
  my_request_failed_credit: "Un pedido falló del lado nuestro. El crédito ({costo}) queda retenido hasta reintentarlo o cancelarlo.",

  ed_overwrite_confirm: '¿Sobrescribir "{molde}" con este código?',
  prof_n_reviews: "{n} reseñas",
  svc_match_score: "match {n}",
  tools_trial_until: "Trial gratis, vence el",
  wiz_page_plan: "Plan de páginas ({n})",
  market_purchase_copied: "¡Listo! Tu compra se copió a",
  trial_activated: "Trial activado. Te acreditamos",
  prv_live_error: "[ ERROR EN VIVO ]:",

  ed_your_apps: "Tus apps ({n})",
  ed_library: "Biblioteca ({n})",
  lego_continue: "Continuar ({n})",
  ind_role: "Rol",

  svc_portfolio_placeholder: "https://miportafolio.com\nhttps://github.com/miusuario",

  dt_no_code: "(sin código: este molde no es REACT_FORJADO)",
  ed_chat_intro: "Pídele que analice, cree o modifique un molde. Carga uno de la izquierda o pega código directo.",
  lego_no_clear_match: "No encontramos una sugerencia clara. Busca manualmente las piezas que necesitas:",
  ind_scan_received: "Escaneo recibido",
  ind_awaiting_scan: "Esperando escaneo",
  ind_upload_manual: "Subir perfil.json a mano",
  my_industrial_project: "Proyecto industrial",
  my_build_installer_tip: "Compilar un instalador nativo (Windows, Linux o Android)",
  my_publish_tip: "Publicar esta app en el marketplace para que otros la compren",
  my_publish_menu_tip: "Publicar esta app: en el Marketplace de MEITI, o generar el paquete para Play Store",
  my_publish_where: "Publicar en",
  my_publish_option_marketplace: "Meiti Marketplace",
  my_publish_option_playstore: "Google Play Store",
  my_publish_option_playstore_tip: "Genera el paquete (.aab) firmado, listo para subir a Play Store a mano",
  my_publish_option_domain: "Dominio Propio",
  my_publish_option_domain_tip: "Todavía no está disponible",
  my_request_change_tip: "Pedir que se le agregue o modifique algo a esta app",
  my_build_queued: "en cola: hay otra compilación en curso, espera unos minutos.",
  my_build_done: "listo ✓",
  my_waiting_generate: "esperando que generes",
  my_in_review: "en revisión",
  my_nothing_to_test: "Todavía no hay nada nuevo que probar. Genera la pantalla pendiente y ahí se aplica el cambio completo.",
  my_sync_when_applied: "Sincroniza cuando el cambio esté aplicado. Por ahora esta copia es idéntica a tu app.",
  my_bring_real_data: "Traer los datos reales que hayan entrado a la app original mientras se revisaba este cambio",
  svc_pay_escrow: "Pagar (retenido)",
  svc_verify_email_note: "Para asignar un dev o liberar un pago necesitamos verificar tu email. Sin contraseñas, y así frenamos spam.",
  svc_save_profile: "Guardar perfil",
  svc_configure: "Configurar",
  svc_opening: "Abriendo...",
  svc_add_package: "Agregar paquete",

  my_export_tip: "Descargar como proyecto standalone, con su propio backend",
  my_installer_shared_note: "Esta app es compartida: vive en un servidor y cada equipo abre su dirección. El instalador de escritorio guardaría los datos aparte en cada máquina, por eso no aparece.",
  my_admin_access: "Acceso de administrador",
  my_admin_access_tip: "Código y pasos para entrar como administrador en la app exportada",
  my_admin_access_none: "Esta app no tiene personal ni páginas de administración: al exportarla, quien la usa es su dueño y no necesita código.",
  my_admin_access_email: "Administrador: {email}",
  my_admin_access_code: "Código de administrador",
  my_admin_access_code_note: "Guárdalo como una contraseña. Con él se entra como administrador aunque el email no funcione.",
  my_admin_access_copy: "Copiar",
  my_admin_access_copied: "Copiado",
  my_admin_access_steps: "Cómo entrar",
  my_admin_access_resend: "Reenviar instrucciones a mi email",
  my_admin_access_sent: "Instrucciones enviadas a {email}.",
  my_admin_access_error: "No se pudo obtener el acceso de administrador.",

  ed_open_with_claude: "Abrir con Claude",
  ed_back_to_molds: "Volver a los moldes",

  ed_talk_to_claude: "Hablar con Claude",

  // ——— SEO / cabecera del navegador ———
  seo_title: 'Crea una app con IA, sin programar | MEITI',
  seo_description: 'Cuéntanos qué app necesitas, en tus palabras. La creamos con IA, sin escribir código. Empieza gratis.',

  // ——— Portada ———
  hero_title: 'Crea tu app con IA. Sin programar.',
  hero_subtitle: 'Describe la app que necesitas. Nosotros la diseñamos, la probamos y te la dejamos lista.',
  hero_help: '¿No sabes cómo empezar? Cuenta para qué la necesitas y quién la va a usar. Con eso alcanza.',
  hero_guide_link: 'Mira la guía de pedidos',

  // ——— Ejemplos de la portada (se cargan en el campo al tocarlos) ———
  example_tasks: 'Lista de tareas del día',
  example_habits: 'Seguimiento de hábitos diarios',
  example_journal: 'Diario personal con estado de ánimo',
  example_expenses: 'Control de gastos del mes',
  example_irrigation: 'Automatizar el riego de un invernadero',

  // ——— Conversación ———
  chat_intro: 'Cuéntame qué app necesitas. Un par de preguntas cortas y la armamos.',
  chat_placeholder: 'Escribe tu respuesta...',
  chat_reintentar: 'Reintentar',
  mode_to_dark: 'Cambiar a modo oscuro',
  mode_to_light: 'Cambiar a modo claro',
  style_pack_label: 'Cómo se arma la pantalla',
  // 💬 [SUGERENCIAS DENTRO DEL CAMPO 2026-08-26] Reemplazan al saludo que vivía arriba de las
  // etiquetas. Van adentro del campo y rotan cada ~4s mientras esté vacío y sin foco. La primera
  // de cada lista es la que decía el saludo viejo; las que siguen recomiendan una acción concreta
  // de ESA pantalla, que es lo que el usuario no sabe cuando se queda mirando el campo en blanco.
  chat_sug_crear: [
    'Cuéntame qué app necesitas y la armamos.',
    'Dime para qué es y quién la va a usar.',
    'Prueba con: "un control de gastos para mi negocio".',
    '¿No sabes por dónde empezar? Toca una idea de arriba.'
  ],
  chat_sug_soporte: [
    'Cuéntame qué pasó, con el detalle que puedas.',
    'Dime en qué pantalla fue y qué esperabas que pasara.',
    'Si es un cobro, pásame la fecha y el monto.'
  ],
  chat_sug_cambio: [
    'Cuéntame qué quieres agregar, cambiar o quitar.',
    'Nombra la pantalla y qué le falta.',
    'Prueba con: "en Clientes, agrega un buscador".',
    'Si algo no funciona, cuéntame qué hiciste y qué viste.'
  ],
  chat_sug_lego: [
    'Cuéntame qué panel quieres armar.',
    'Dime qué datos vas a manejar y quién los carga.',
    'Prueba con: "un tablero de tareas con estados".'
  ],
  chat_sug_editor: [
    'Pídele que analice, cree o modifique un molde.',
    'Lee y modifica los moldes de la app por su cuenta.',
    'Prueba con: "revisa este molde y dime qué está mal".'
  ],
  chat_sug_industrial: [
    'Cuéntame qué máquina quieres automatizar.',
    'Dime qué sensores o motores tiene.',
    'Prueba con: "encender una bomba cuando baje el nivel".'
  ],
  chat_sug_servicios: [
    'Cuéntanos qué necesitas y armamos el pedido.',
    'Dinos para cuándo lo necesitas.',
    'Cuanto más concreto, mejor te cotiza el dev.'
  ],
  chat_charla_en_proceso: 'Tienes una charla sin terminar.',
  chat_continuar_charla: 'Continuar',
  chat_empezar_de_nuevo: 'Empezar de nuevo',

  // ——— Repaso del pedido ———
  review_title: 'Revisa tu pedido',
  review_anything_else: '¿Algo más para agregar o corregir?',
  review_anything_else_optional: '¿Algo más para agregar o corregir? (opcional)',

  // ——— Estilo ———
  style_title: 'Elige un estilo para tu app',
  style_subtitle: 'Después siempre se puede cambiar.',
  style_minimal: 'Minimalista',
  style_warm: 'Cálido',
  style_dark: 'Oscuro elegante',
  style_colorful: 'Colorido',
  style_professional: 'Profesional',

  // ——— Nivel de complejidad ———
  level_basic: 'Básica',
  level_basic_desc: '1-2 pantallas, lo esencial para empezar a usarla ya.',
  level_complete: 'Completa',
  level_complete_desc: 'Varias pantallas, formularios y configuración. Una app real de uso diario.',
  level_advanced: 'Avanzada',
  level_advanced_desc: 'La versión más completa posible, con más funciones y detalle.',

  // ——— Créditos y pago ———
  credits_added: '¡Créditos acreditados! Ya puedes seguir.',
  credits_payment_cancelled: 'Pago cancelado. No se cobró nada.',
  credits_missing_title: 'Te faltan créditos',
  credits_buy: 'Comprar créditos',

  // ——— Cierre ———
  done_title: '¡Recibimos tu pedido!',
  done_email_optional: 'o deja tu email (opcional)',

  // ——— Errores ———
  email_api_key_placeholder: 'Tu API key de Resend',

  error_generic: 'Algo salió mal',
  error_payment_start: 'No se pudo iniciar el pago de créditos.',
  error_assistant_silent: 'El asistente no respondió.',
  error_assistant_connection: 'Fallo de conexión con el asistente.',
  error_not_enough_credits: 'No te alcanzan los créditos para crear esta app.',
  error_notice_failed: 'No se pudo activar el aviso. Puedes revisar en "Mis apps".'
};
